(function(){
    'use strict';
    var chats=new Set(),lessons=new Set(),admins=new Set(),actions=new Map(),lastMenuChat=null,pressTimer=null,pressStart=null,bypass=false,bar=null;
    function ar(){return /^(ar|ur)(-|$)/.test(String(document.documentElement.lang||'ar').toLowerCase())}
    function ensureBar(){if(bar)return bar;var s=document.createElement('style');s.textContent='#omranSelectionBar{position:fixed;top:0;left:0;right:0;z-index:2147483000;display:none;align-items:center;gap:12px;min-height:58px;padding:calc(8px + env(safe-area-inset-top,0px)) 14px 8px;background:#fff;color:#202124;box-shadow:0 3px 16px rgba(0,0,0,.22);direction:rtl}#omranSelectionBar.show{display:flex}#omranSelectionCancel,#omranSelectionTrash{width:42px;height:42px;border:0;border-radius:50%;display:grid;place-items:center;background:transparent;color:#202124;cursor:pointer}#omranSelectionTrash{color:#c5221f}#omranSelectionCount{flex:1;font-size:17px;font-weight:800;text-align:start}.omran-selectable{position:relative;-webkit-user-select:none;user-select:none}.omran-select-mark{position:absolute;top:8px;inset-inline-start:8px;z-index:12;width:23px;height:23px;border-radius:50%;border:2px solid rgba(120,120,120,.75);background:rgba(255,255,255,.94);display:none;align-items:center;justify-content:center;color:#fff;font-size:14px;font-weight:900;box-sizing:border-box;pointer-events:none}.omran-selection-mode .omran-select-mark{display:flex}.omran-selected{outline:3px solid #16a34a!important;outline-offset:-3px;background:rgba(22,163,74,.12)!important}.omran-selected .omran-select-mark{display:flex;background:#16a34a;border-color:#16a34a}.omran-selection-mode .hist-menu-btn,.omran-selection-mode .eduDelBtn{visibility:hidden!important}@media(max-width:600px){#omranSelectionBar{min-height:54px;padding-inline:10px}#omranSelectionCount{font-size:16px}}';(document.head||document.documentElement).appendChild(s);var el=document.createElement('div');el.id='omranSelectionBar';el.setAttribute('role','toolbar');el.innerHTML='<button id="omranSelectionCancel" type="button" aria-label="إلغاء التحديد">✕</button><div id="omranSelectionCount">0</div><button id="omranSelectionTrash" type="button" aria-label="حذف المحدد"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></button>';document.body.appendChild(el);el.querySelector('#omranSelectionCancel').onclick=clear;el.querySelector('#omranSelectionTrash').onclick=removeSelected;bar=el;return bar}
    function total(){return chats.size+lessons.size+admins.size+actions.size}
    function refresh(){ensureBar();var n=total();bar.classList.toggle('show',n>0);document.documentElement.classList.toggle('omran-selection-mode',n>0);var cntEl=bar.querySelector('#omranSelectionCount'),cntTxt=n+' '+(ar()?(n===1?'عنصر محدد':'عناصر محددة'):(n===1?'selected item':'selected items'));if(cntEl.textContent!==cntTxt)cntEl.textContent=cntTxt;document.querySelectorAll('.hist-item').forEach(function(el){el.classList.toggle('omran-selected',chats.has(String(el.dataset.pid||'')))});document.querySelectorAll('.eduLessonRow').forEach(function(el){el.classList.toggle('omran-selected',lessons.has(String(el.dataset.id||'')))});document.querySelectorAll('[data-omran-admin]').forEach(function(el){el.classList.toggle('omran-selected',admins.has(el.getAttribute('data-omran-admin')))});actions.forEach(function(v){if(v&&v.el)v.el.classList.add('omran-selected')})}
    function clear(){chats.clear();lessons.clear();admins.clear();actions.forEach(function(v){if(v&&v.el)v.el.classList.remove('omran-selected')});actions.clear();refresh()}
    function mark(el){if(!el||el.querySelector(':scope > .omran-select-mark'))return;el.classList.add('omran-selectable');var m=document.createElement('span');m.className='omran-select-mark';m.textContent='✓';el.appendChild(m)}
    function scan(){document.querySelectorAll('.hist-item,.eduLessonRow').forEach(mark);document.querySelectorAll('[onclick*="adminDeleteUser"]').forEach(function(btn){var oc=btn.getAttribute('onclick')||'',m=oc.match(/adminDeleteUser\(['"]([^'"]+)/);if(!m)return;var row=btn.closest('div');if(row){row.setAttribute('data-omran-admin',m[1]);mark(row)}})}
    function toggle(el,force){if(!el)return;var id;if(el.classList.contains('hist-item')){id=String(el.dataset.pid||'');if(!id)return;(force===true||!chats.has(id))?chats.add(id):chats.delete(id)}else if(el.classList.contains('eduLessonRow')){id=String(el.dataset.id||'');if(!id)return;(force===true||!lessons.has(id))?lessons.add(id):lessons.delete(id)}else if(el.hasAttribute('data-omran-admin')){id=el.getAttribute('data-omran-admin');(force===true||!admins.has(id))?admins.add(id):admins.delete(id)}refresh()}
    function chooseAllChats(){try{state.projects.forEach(function(p){if(p&&p.id)chats.add(String(p.id))})}catch(e){document.querySelectorAll('.hist-item').forEach(function(x){if(x.dataset.pid)chats.add(String(x.dataset.pid))})}refresh()}
    function chooseCurrent(){var id='';try{id=String(state.currentId||'')}catch(e){}var el=id&&document.querySelector('.hist-item[data-pid="'+CSS.escape(id)+'"]');if(el)toggle(el,true);else if(id){chats.add(id);refresh()}}
    function deleteChats(ids){if(!ids.length)return;try{ids.forEach(function(id){if(window.chatsMarkDeleted)window.chatsMarkDeleted(id)});state.projects=state.projects.filter(function(p){return ids.indexOf(String(p.id))<0});if(!state.projects.length){var nid='p_'+Date.now();state.projects.push({id:nid,title:typeof t==='function'?t('defaultProjectTitle'):'محادثة جديدة',messages:[],code:''})}if(!state.projects.some(function(p){return p.id===state.currentId}))state.currentId=state.projects[state.projects.length-1].id;if(typeof mahaClearImageRef==='function')mahaClearImageRef();saveState();renderAll();var tok=typeof chatsAuthToken==='function'?chatsAuthToken():'';if(tok)fetch('/api/account?action=chats_delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:tok,ids:ids})}).catch(function(){})}catch(e){console.error('batch chat delete',e)}}
    async function deleteLessons(ids){if(!ids.length)return;try{await Promise.all(ids.map(function(id){return deleteLesson(id)}));if(typeof showHome==='function')showHome()}catch(e){console.error('batch lesson delete',e)}}
    async function deleteAdmins(names){for(var i=0;i<names.length;i++){try{var token=typeof authGet==='function'?authGet('aiapp_auth_token'):'',r=await fetch('/api/admin-actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token,action:'delete',targetUsername:names[i]})});if(r.ok&&window.__adminUsersCache)window.__adminUsersCache=window.__adminUsersCache.filter(function(x){return x.username!==names[i]})}catch(e){console.error('batch admin delete',e)}}try{if(typeof renderAdminUserTable==='function')renderAdminUserTable()}catch(e){}}
    async function removeSelected(){var ci=Array.from(chats),li=Array.from(lessons),ai=Array.from(admins),act=Array.from(actions.values());clear();deleteChats(ci);await deleteLessons(li);await deleteAdmins(ai);if(act.length){var nativeConfirm=window.confirm;bypass=true;window.confirm=function(){return true};try{act.forEach(function(a){if(a&&a.el&&a.el.isConnected)a.el.click()})}finally{window.confirm=nativeConfirm;bypass=false}}}
    function selectAction(el,label){var key=el.id||el.getAttribute('onclick')||label||String(Date.now());actions.set(key,{el:el,label:label});refresh()}
    /* v-delete-direct: زرّ «حذف» يحذف مباشرة (بتأكيده الأصلي) ما لم يكن وضع التحديد بالضغط المطوّل فعّالًا — كان يحوّل كل ضغطة حذف إلى «تحديد» فقط فبدت المحادثة كأنها لا تُحذف. */
    function interceptDelete(el,e){if(!el||bypass||!total())return false;var id=el.id||'',oc=el.getAttribute('onclick')||'';if(id==='btnDeleteAll'||id==='omranFootDelete'||oc.indexOf('appFullCleanup')>=0){e.preventDefault();e.stopImmediatePropagation();chooseAllChats();return true}if(id==='btnDeleteChat'){e.preventDefault();e.stopImmediatePropagation();chooseCurrent();return true}if(el.classList.contains('eduDelBtn')){e.preventDefault();e.stopImmediatePropagation();toggle(el.closest('.eduLessonRow'),true);return true}if(oc.indexOf('adminDeleteUser')>=0){e.preventDefault();e.stopImmediatePropagation();toggle(el.closest('[data-omran-admin]'),true);return true}if(el.classList.contains('danger')&&lastMenuChat){e.preventDefault();e.stopImmediatePropagation();toggle(lastMenuChat,true);return true}var label=[id,el.className||'',el.title||'',el.getAttribute('aria-label')||'',el.textContent||''].join(' ');if(id==='fDel'||/(^|\s)(delete|trash)(\s|$)|حذف|مسح نهائي/i.test(label)){e.preventDefault();e.stopImmediatePropagation();selectAction(el,String(el.title||el.textContent||'').trim());return true}return false}
    document.addEventListener('pointerdown',function(e){var el=e.target.closest&&e.target.closest('.hist-item,.eduLessonRow,[data-omran-admin]');if(!el)return;pressStart={x:e.clientX,y:e.clientY,el:el};pressTimer=setTimeout(function(){pressTimer=null;toggle(el,true);try{navigator.vibrate&&navigator.vibrate(25)}catch(_){}},520)},true);
    document.addEventListener('pointermove',function(e){if(pressTimer&&pressStart&&(Math.abs(e.clientX-pressStart.x)>10||Math.abs(e.clientY-pressStart.y)>10)){clearTimeout(pressTimer);pressTimer=null}},true);['pointerup','pointercancel'].forEach(function(name){document.addEventListener(name,function(){if(pressTimer){clearTimeout(pressTimer);pressTimer=null}},true)});
    document.addEventListener('contextmenu',function(e){var el=e.target.closest&&e.target.closest('.hist-item,.eduLessonRow,[data-omran-admin]');if(el&&total()){e.preventDefault()}},true);
    document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('#omranSelectionBar'))return;/* v-delete-trash-fix: زرّ سلّة الشريط كان يُعترض كأنه «زرّ حذف» فلا يعمل أبدًا */var menu=e.target.closest&&e.target.closest('.hist-menu-btn');if(menu)lastMenuChat=menu.closest('.hist-item');var del=e.target.closest&&e.target.closest('button,[role="button"],a');if(del&&interceptDelete(del,e))return;if(!total())return;var item=e.target.closest&&e.target.closest('.hist-item,.eduLessonRow,[data-omran-admin]');if(item){e.preventDefault();e.stopImmediatePropagation();toggle(item)}},true);
    /* v-delete-freeze-fix: كان المراقب يعيد كتابة نص العدّاد عند كل تغيّر في الصفحة، وكتابته تغيّرٌ بدوره — حلقة لا نهائية جمّدت التطبيق كله. الآن: تجاهل تغيّرات الشريط نفسه، ودمج الفحص في إطار واحد. */
    var pendingScan=0;new MutationObserver(function(muts){var own=true;for(var i=0;i<muts.length;i++){if(!(bar&&bar.contains(muts[i].target))){own=false;break}}if(own||pendingScan)return;pendingScan=requestAnimationFrame(function(){pendingScan=0;scan();refresh()})}).observe(document.documentElement,{childList:true,subtree:true});scan();
    })();