(function(){
var APP_THEMES={gold:['#d4af37','212,175,55','#e8c766']};
var CHECK='<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';
window.applyAppTheme=function(n,save){var t=APP_THEMES[n]||APP_THEMES.gold;if(!APP_THEMES[n])n='gold';var r=document.documentElement.style;r.setProperty('--accent',t[0]);r.setProperty('--accent-rgb',t[1]);r.setProperty('--accent-light',t[2]);if(save){try{localStorage.setItem('appTheme',n);var th=JSON.parse(localStorage.getItem('aiapp_theme')||'{}');th.accent=t[0];localStorage.setItem('aiapp_theme',JSON.stringify(th));}catch(e){ __swallow(e, "save:index#1"); }}var w=document.getElementById('themeCircles');if(w)Array.prototype.forEach.call(w.children,function(b){var on=b.dataset.theme===n;b.style.outline=on?'2px solid '+t[0]:'none';b.style.outlineOffset='3px';b.innerHTML=on?CHECK:'';});};
function initCircles(){var w=document.getElementById('themeCircles');if(w&&!w.children.length){Object.keys(APP_THEMES).forEach(function(k){var b=document.createElement('button');b.type='button';b.dataset.theme=k;b.setAttribute('aria-label',k);b.style.cssText='width:32px;height:32px;border-radius:50%;border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;padding:0;background:'+APP_THEMES[k][0]+';';b.onclick=function(){applyAppTheme(k,true);};w.appendChild(b);});}var saved='gold';try{saved=localStorage.getItem('appTheme')||'gold';}catch(e){ __swallow(e, "misc:index#3"); }applyAppTheme(saved,false);}
var TICKER_COLORS=['#ffffff','#d4af37','#3b82f6','#06b6d4','#10b981','#f59e0b','#f97316','#ec4899'];
window.applyTickerColor=function(c,save){var t=document.getElementById('stockTickerTrack');if(t)t.style.color=c;if(save){try{localStorage.setItem('tickerColor',c);}catch(e){ __swallow(e, "save:index#4"); }}var w=document.getElementById('tickerColorCircles');if(w)Array.prototype.forEach.call(w.children,function(b){var on=b.dataset.c===c;b.style.outline=on?'2px solid '+c:'none';b.style.outlineOffset='2px';});};
function initTickerColors(){var w=document.getElementById('tickerColorCircles');if(w&&!w.children.length){TICKER_COLORS.forEach(function(c){var b=document.createElement('button');b.type='button';b.dataset.c=c;b.setAttribute('aria-label',c);b.style.cssText='width:26px;height:26px;border-radius:50%;border:1px solid rgba(255,255,255,.25);cursor:pointer;padding:0;flex:0 0 auto;background:'+c+';';b.onclick=function(){applyTickerColor(c,true);};w.appendChild(b);});}var saved='#ffffff';try{saved=localStorage.getItem('tickerColor')||'#ffffff';}catch(e){ __swallow(e, "misc:index#5"); }applyTickerColor(saved,false);}
function initThemeUI(){initCircles();initTickerColors();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initThemeUI);}else{initThemeUI();}
})();
