// Shared language strings for terms.html / privacy.html
const LEGAL_LANGS = {
  ar: { dir:'rtl', dateLocale:'ar-EG', back:'⚡ الرجوع إلى Omran AI Builder',
    termsTitle:'الشروط والأحكام', privacyTitle:'سياسة الخصوصية',
    updated:'آخر تحديث' },
  en: { dir:'ltr', dateLocale:'en-US', back:'⚡ Back to Omran AI Builder',
    termsTitle:'Terms & Conditions', privacyTitle:'Privacy Policy',
    updated:'Last updated' },
  fr: { dir:'ltr', dateLocale:'fr-FR', back:'⚡ Retour à Omran AI Builder',
    termsTitle:'Conditions Générales', privacyTitle:'Politique de Confidentialité',
    updated:'Dernière mise à jour' },
  hi: { dir:'ltr', dateLocale:'hi-IN', back:'⚡ Omran AI Builder पर वापस जाएँ',
    termsTitle:'नियम व शर्तें', privacyTitle:'गोपनीयता नीति',
    updated:'अंतिम अपडेट' },
  ur: { dir:'rtl', dateLocale:'ur-PK', back:'⚡ Omran AI Builder پر واپس جائیں',
    termsTitle:'شرائط و ضوابط', privacyTitle:'رازداری کی پالیسی',
    updated:'آخری تازہ کاری' },
  bn: { dir:'ltr', dateLocale:'bn-BD', back:'⚡ Omran AI Builder এ ফিরে যান',
    termsTitle:'শর্তাবলী', privacyTitle:'গোপনীয়তা নীতি',
    updated:'সর্বশেষ আপডেট' },
  ne: { dir:'ltr', dateLocale:'ne-NP', back:'⚡ Omran AI Builder मा फर्कनुहोस्',
    termsTitle:'नियम र सर्तहरू', privacyTitle:'गोपनीयता नीति',
    updated:'अन्तिम अपडेट' },
};
