// v-studio-14: أوامر الميزات الأربع عشرة الجديدة لستايل الذكاء الاصطناعي (تُدمج في studio-create)
'use strict';
const STYLE_PROMPTS = {
 "idphoto": {
  "white": "an official ID photo with a plain pure white background, head-and-shoulders framing, even soft studio lighting, neat formal attire",
  "blue": "an official ID photo with a plain light blue background, head-and-shoulders framing, even soft studio lighting, neat formal attire",
  "passport": "a passport-style photo: plain white background, face centered and fully visible, neutral expression, head-and-shoulders framing",
  "residence": "a residence / ID card photo: plain light background, centered face, neutral expression, formal collar",
  "suit": "a professional portrait wearing a tailored dark formal suit with a white shirt, plain neutral background",
  "kandoraformal": "a formal portrait wearing a crisp white kandora with a white ghutra and black agal, plain neutral background",
  "linkedin": "a professional LinkedIn headshot: smart business attire, soft studio light, blurred neutral grey background, confident subtle smile",
  "graduation": "a graduation portrait wearing a black graduation gown and cap with a tassel, plain elegant background"
 },
 "hijab": {
  "gulf": "a Gulf-style hijab: a flowing black sheila draped loosely with an elegant black abaya",
  "turkish": "a Turkish-style hijab: a structured satin scarf neatly wrapped and pinned, with a modest chic outfit",
  "modern": "a modern minimal hijab wrap in a soft neutral tone with a contemporary modest outfit",
  "shayla": "a classic black shayla with a plain black abaya",
  "colored": "a colored abaya in a rich jewel tone with a matching hijab",
  "embroidered": "a black abaya with fine gold embroidery and a matching embroidered sheila",
  "sport": "a sport hijab with a modest athletic outfit",
  "bridal": "a bridal white hijab with delicate lace and pearls over an elegant white gown",
  /* v-studio-more-looks (طلب المالك «زيد الأشكال») */
  "khaleejiwrap": "a Gulf evening wrap: a sheer embellished sheila draped over one shoulder with a crystal-trimmed edge and an elegant kaftan",
  "layered": "a layered hijab: an inner cap with two contrasting soft scarves wrapped one over the other, one falling long at the back",
  "turban": "a neatly wrapped turban-style hijab with a knot at the front and a matching modern outfit",
  "silkprint": "a printed silk hijab in a patterned design, loosely wrapped, with a plain matching outfit"
 },
 "gulfmen": {
  "whiteghutra": "a white kandora with a crisp white ghutra and black agal",
  "redshemagh": "a white thobe with a red-and-white checkered shemagh and black agal",
  "bwshemagh": "a white thobe with a black-and-white checkered shemagh and black agal",
  "cobra": "a white kandora with a white ghutra folded in the raised \"cobra\" style with agal",
  "hamdaniya": "a white kandora with a white hamdaniya headscarf wrapped Emirati style without agal",
  "coloredkandora": "a colored kandora in soft grey or beige with a white ghutra and agal",
  "qatari": "a Qatari-style white thobe with a stiff white ghutra draped in the Qatari way and agal",
  "kuwaiti": "a Kuwaiti-style white dishdasha with a Kuwaiti collar, white ghutra and agal",
  /* v-studio-more-looks */
  "winterbisht": "a dark winter bisht with heavy gold zari trim worn over a white kandora, with a white ghutra and agal",
  "omanikummah": "an Omani dishdasha with an embroidered kummah cap and a silver khanjar belt",
  "wintercoat": "a white kandora with a tailored dark wool overcoat and a white ghutra, a modern Gulf winter look",
  "bahrainiattire": "a Bahraini-style white thobe with a lightly starched white ghutra and a black agal"
 },
 "menhair": {
  "fade": "a clean skin-fade haircut with a short textured top",
  "pompadour": "a voluminous pompadour hairstyle",
  "curlytop": "a curly top with faded sides",
  "manbun": "long hair tied up in a man bun",
  "buzz": "a very short buzz cut",
  "longmen": "shoulder-length long hair for men",
  "sidepart": "a classic side-part hairstyle",
  "undercut": "a disconnected undercut with a slicked-back top",
  "quiff": "a textured quiff hairstyle",
  "afro": "a natural afro hairstyle"
 },
 /* v-studio-variety (شكوى المالك ٢٨ سبتمبر «كلّهم نوع واحد»): كلّ خيار يذكر لونه ونقشه
    وكثافته وموضعه صراحةً — الوصف السطر الواحد كان يخرج نقشًا عامًّا واحدًا مهما اختار. */
 "henna": {
  "gulfhenna": "delicate Gulf (Khaleeji) henna in a warm reddish-brown stain: thin flowing floral vines, small leaves and fine dotted borders drawn along the fingers and the back of the hand, with plenty of bare skin left between the motifs",
  "indianhenna": "dense traditional Indian bridal mehndi in a deep reddish-brown stain: paisley (buta) motifs, peacocks, fine lace netting and a mandala centre on the palm, covering the hand almost edge to edge with very little bare skin",
  "sudanese": "bold Sudanese henna in a very dark, almost black stain: large thick geometric blocks, oversized floral motifs and wide filled bands with sharp empty gaps between them",
  "bridalhenna": "elaborate bridal henna in a rich reddish-brown stain: a full mandala on the palm with dense vines and jaali netting running from the fingertips up over the wrists to the forearms, edged with tiny pearl-like dots",
  "minimal": "a small minimalist henna design in a light reddish-brown stain: one single delicate motif only — a thin vine, a tiny flower or a fine bracelet line on the back of one hand — with all the rest of the skin completely bare",
  "feet": "traditional henna on the feet and ankles in a reddish-brown stain: an anklet-style band around each ankle with floral motifs spreading over the top of the foot and onto the toes, the hands left bare",
  "whitehenna": "white henna body paint in opaque bright white, NOT brown at all: raised lace-like patterns, fine pearl dots and delicate floral lace cuffs, clearly standing out white against the skin",
  "khidab": "black khidab henna in a deep glossy black stain: bold thick blocks and heavily filled motifs on the fingertips and the back of the hand, strongly contrasting against the skin",
  "moroccan": "Moroccan (Berber) henna in a reddish-brown stain: sharp symmetrical geometry — diamonds, triangles, chevrons and straight hatched lines — with no floral motifs at all",
  "cuff": "a henna cuff in a reddish-brown stain: a wide ornamented bracelet band wrapped around the wrist with fine tassels hanging from it, the fingers and the rest of the hand left completely bare",
  "fingertips": "the classic Gulf dipped-fingertip henna in a dark reddish-brown stain: the fingertips fully dipped in solid henna up to the first knuckle with a neat straight edge, and nothing else drawn on the hand",
  "glitterhenna": "festive henna in a reddish-brown stain traced over with gold glitter gel and tiny crystal accents that catch the light along the outlines of the pattern",
  /* v-henna-100 (طلب المالك «على الأقلّ ١٠٠ نوع وشكل»): مدارس وأصول، مواضع، نقوش، ألوان، مناسبات، وترند */
  "emirati": "fine Emirati khaleeji henna: thin flowing vines running along the fingers with one small open flower on the back of the hand, most of the skin left bare",
  "najdi": "Najdi Saudi henna: bold symmetrical panels framed by thick straight borders, with simple solid-filled shapes inside them",
  "kuwaitihenna": "Kuwaiti henna: dense fine lace covering the back of the hand and ending in a scalloped shell edge at the wrist",
  "qatarihenna": "Qatari henna: one large open floral medallion centred on the back of the hand with fine stems trailing onto the fingers",
  "omanihenna": "Omani henna: a sharp geometric grid of small squares and triangles filled in alternately, in a very dark stain",
  "bahrainihenna": "Bahraini henna: delicate pearl-inspired strands of dots looping around the fingers and gathering at the wrist",
  "yemenihenna": "Yemeni naqsh: thick blackish-brown blocks with very fine bare lines carved through them, a strong negative-space look",
  "somalihenna": "Somali henna: long slender vertical vines running from the fingertips down the back of the hand with tiny paired leaves",
  "egyptianhenna": "Egyptian henna: lotus flowers and simple papyrus-style repeating borders in a warm reddish-brown stain",
  "turkishhenna": "Turkish kina: one solid filled circle in the centre of the palm with a plain clean edge, the classic henna-night mark",
  "persianhenna": "Persian henna: fine repeating paisley (boteh) motifs in a soft reddish stain with delicate thin outlines",
  "pakistani": "Pakistani mehndi: extremely fine dense line work, jaali netting and floral clusters covering the hand and wrist together",
  "rajasthani": "Rajasthani mehndi: figurative panels — peacocks, dancing figures and little arches — drawn in dense fine lines",
  "marwari": "Marwari mehndi: boldly outlined motifs with thick solid fills and heavy contrast between dark shapes and bare skin",
  "malayinai": "Malay inai: fingertips and nails stained solid dark with simple soft floral dots scattered over the knuckles",
  "tunisian": "Tunisian henna: fine geometric triangles arranged into one large diamond in the centre of the palm",
  "africanhenna": "West African henna: wide bold bands and solid blocks with strong straight edges, covering hands and wrists",
  "fusionhenna": "a fusion design: an Indian dense mandala centre surrounded by open Gulf-style trailing vines and bare skin",
  "palmfull": "a full palm design covering the whole palm from edge to edge, symmetrical and dense, with the back of the hand left bare",
  "backhand": "a design placed only on the back of the hand within a clear rounded outline, the fingers left completely bare",
  "fingersonly": "fine bands and tiny motifs drawn on the fingers only, with the palm and the back of the hand completely bare",
  "fingerbands": "thin ring-like henna bands drawn around each finger joint like stacked rings, nothing else on the hand",
  "thumbmotif": "one detailed motif drawn on the thumb alone, with every other part of the hand left completely bare",
  "knuckles": "small repeated motifs drawn on the knuckles only, spaced evenly, with the rest of the hand bare",
  "wristband": "a single ornamented band wrapped around the wrist only, the hand itself left completely bare",
  "halfhand": "a diagonal design covering exactly half the hand with a sharp straight edge across it and bare skin on the other half",
  "forearmhenna": "the design continues from the hand up the forearm in a tapering vine that narrows as it climbs",
  "glovehenna": "full glove coverage: dense pattern from the fingertips to the wrist with almost no bare skin anywhere",
  "anklecuff": "an ornate anklet band wrapped around the ankle with small drops hanging from its lower edge",
  "solefoot": "a rounded motif placed on the sole and heel of the foot with a plain clean border around it",
  "bothhands": "a mirrored design spread across both hands so the two halves complete one picture when the hands are held together",
  "sidehand": "a narrow vine running along the outer edge of the hand from the little finger down to the wrist",
  "shoulderhenna": "a floral spray of henna over the shoulder and collarbone with fine trailing tips",
  "neckhenna": "a small delicate motif placed at the side of the neck just below the ear, fine lines and a few dots, nothing else",
  "armband": "a wide ornamented band wrapped around the upper arm with a repeating pattern and a thin border along both of its edges",
  "centrepalm": "one mandala centred in the middle of the palm with fine rays radiating out towards the fingers",
  "backfinger": "one fine continuous line running down the length of a single finger with tiny dots along it",
  "mandalahenna": "a large concentric mandala built from repeating rings of petals, dots and fine arcs",
  "peacock": "a peacock with a sweeping feathered tail spreading across the hand, drawn in fine detailed lines",
  "paisleyhenna": "repeating paisley teardrops of different sizes, each one filled with a different fine texture",
  "floralvine": "a continuous flowering vine winding across the skin with open blossoms, buds and small leaves",
  "rosegarden": "realistic layered roses with shaded petals and thorny stems, a modern floral henna look",
  "lotushenna": "stylised lotus flowers opening in symmetrical layers with fine line detail between the petals",
  "jaali": "a fine jaali net of tiny diamonds covering the area like lattice, with bolder motifs sitting on top of it",
  "checkerhenna": "a checkerboard of small squares filled in alternately, sharp and graphic, with a plain thin frame drawn around the whole block",
  "dotsgrid": "a pattern built entirely from dots of different sizes arranged in ordered rows and clusters",
  "chevronhenna": "bands of zigzag chevrons stacked in parallel rows with thin straight lines separating each row from the next",
  "leaveshenna": "overlapping leaf shapes with finely veined interiors arranged along one curving stem that runs across the skin",
  "butterfly": "delicate butterflies at different sizes with finely patterned wings, as if landing on the skin",
  "heartshenna": "small linked hearts forming a continuous chain, each one with a fine dotted outline and a tiny filled centre",
  "celestial": "crescent moons and scattered stars with fine radiating rays, a celestial night design",
  "waveshenna": "flowing wave curves layered over each other with fine spray dots along their crests",
  "featherhenna": "long feathers with split barbs drawn in fine strokes, trailing small dots at their tips",
  "arabesque": "an Islamic arabesque of interlacing geometric stars joined by continuous ribbon lines that never break",
  "calligraphyhenna": "an elegant Arabic calligraphy word as the centrepiece, woven into a light frame of fine flowers and trailing stems",
  "initialshenna": "a single decorated Arabic or Latin letter as the centrepiece, surrounded by fine trailing vines and small dots",
  "evileye": "an evil-eye motif at the centre with protective dotted rings around it and fine lashes radiating outwards",
  "khamsa": "a khamsa (hand of Fatima) motif filled with fine geometric detail and framed by a thin double outline",
  "palmtree": "slender palm trees with detailed fronds standing over a fine dune line, with a small sun disc behind them",
  "falconhenna": "a falcon with detailed feathering, wings folded, drawn in strong confident lines",
  "camelhenna": "a camel silhouette with an ornamented saddle blanket and fine dune lines around it",
  "lacework": "a lace-like pattern of tiny loops and scallops as if fabric lace were laid on the skin",
  "swirls": "large open spirals and curls flowing into one another with long tapering tails and tiny dots in the gaps",
  "tribalhenna": "a bold tribal pattern of thick pointed shapes and strong straight lines with heavy black-brown fill",
  "abstractlines": "free abstract lines of varying thickness crossing the skin with no repeating motif",
  "botanical": "a realistic botanical sprig — wheat, olive or eucalyptus — with finely shaded leaves",
  "bohohenna": "a bohemian mix of triangles, arrows, crescent moons and dangling chains of dots, loosely arranged and asymmetric",
  "darkmaroon": "the same fine design stained a very deep maroon, almost wine-coloured, rich and saturated",
  "redblack": "a two-tone design: reddish-brown henna outlined and accented with black khidab for strong contrast",
  "ombrehenna": "a design that fades gradually from a deep dark stain at the fingertips to a light stain at the wrist",
  "glossgel": "a glossy gel-finish design that catches the light along its lines while the stain underneath stays natural",
  "mattestain": "a completely matte natural stain with no shine at all, soft and skin-like, the pattern reading by colour alone",
  "crystalhenna": "a fine design studded with a few tiny crystal stones placed at the centres of the motifs",
  "pearlhenna": "a delicate design finished with tiny pearl beads placed along its outer edges and at the centre of each motif",
  "silverglitter": "a stain traced over with silver glitter gel that follows every outline of the pattern",
  "goldleafhenna": "a design accented with small flakes of gold leaf pressed onto the darkest parts of the pattern",
  "neonhenna": "a modern coloured body-paint design in bright neon tones instead of a brown stain",
  "pastelhenna": "a soft pastel-coloured body-paint design in pink, mint and lilac tones instead of a brown stain, gently blended",
  "twotone": "a design split into two colours: one half in a classic brown stain and the other in opaque white",
  "glowhenna": "a stain finished with a fine shimmer dust that gives a soft sparkle across the whole pattern",
  "hennanightfull": "a full festive henna-night design covering hands and wrists densely, celebratory and elaborate",
  "engagementhenna": "an engagement design built around a ring motif on the finger with fine vines spreading from it",
  "eidhenna": "a festive Eid design with crescents, lanterns and small stars worked into a light floral frame",
  "ramadanhenna": "a quiet Ramadan design with lantern and mosque-arch motifs drawn in fine restrained lines",
  "newbornhenna": "a gentle celebration design with tiny footprints, a crescent and small stars in a light stain",
  "graduationhenna": "a graduation design with a small cap motif and a laurel of fine leaves around it",
  "birthdayhenna": "a playful design with balloons, tiny candles and confetti dots scattered across the skin",
  "nationaldayhenna": "a national-day design with a falcon, small flags and palm fronds drawn in fine lines",
  "guesthenna": "a light wedding-guest design: one elegant motif on the back of the hand with a thin wrist band",
  "festivalhenna": "a bold festival design mixing glitter, bright colour accents and large graphic shapes across the hand and wrist",
  "fineline": "an ultra-fine single-line design drawn with a very thin cone, minimal and precise",
  "negativespace": "a design where the pattern is defined by thick dark fill around bare skin shapes rather than by drawn lines",
  "tattoostyle": "a blackwork tattoo-style design with solid black-brown shapes and sharp geometric edges",
  "handharness": "a jewellery-style harness: a ring motif on the finger joined by fine chains to a band at the wrist",
  "watchband": "a henna wristwatch: a decorated round face on the wrist with a patterned strap around it",
  "daintyhenna": "a few tiny scattered motifs — a flower, a leaf, three dots — spaced far apart on bare skin",
  "geometricmodern": "a modern geometric design of clean triangles, thin parallel lines and one solid filled shape",
  "kidshenna": "a simple playful design for a child: a small flower, a star and a tiny heart in a light stain",
  "menssimple": "a simple bold design suited to a man's hand: one strong geometric band across the back of the hand, nothing delicate or floral",
  "bracelettassel": "a wide wrist cuff with long fine tassels of dots hanging from its lower edge over the back of the hand"
 },
 "wedding": {
  "bride": "a classic white bridal gown with a veil, elegant bridal makeup and an updo",
  "gulfbride": "a luxurious Gulf bridal look: ornate white gown, gold jewelry, glamorous makeup",
  "groom": "a sharp black tuxedo with a bow tie and groomed hair",
  "gulfgroom": "a Gulf groom look: white kandora, white ghutra, black agal and a gold-trimmed bisht",
  "indianbride": "an Indian bridal lehenga in red and gold with heavy jewelry and bridal makeup",
  "moroccanbride": "a Moroccan bridal caftan with an ornate gold belt and jewelry",
  "engagement": "an elegant engagement outfit in soft pastel with refined makeup",
  "hennanight": "a henna-night look: traditional embroidered dress in green and gold tones with festive jewelry",
  /* v-studio-more-looks */
  "milkah": "a Gulf katb-al-kitab (milkah) look: a modest white embroidered gown with a light veil and delicate gold jewellery",
  "receptionsuit": "a reception look: a tailored ivory tuxedo with a black bow tie and a boutonniere",
  "turkishbride": "a Turkish bridal look: a fitted lace gown with long sleeves and a cathedral veil with a jewelled headband",
  "gardenparty": "a garden-wedding guest look: a flowing pastel chiffon gown with floral hair styling and light jewellery"
 },
 "accessories": {
  "watch": "a luxury wristwatch",
  "earrings": "elegant statement earrings",
  "necklace": "a fine gold necklace",
  "hat": "an elegant wide-brim hat",
  "cap": "a sporty baseball cap",
  "bag": "a luxury designer handbag",
  "bracelet": "stacked gold bracelets",
  "scarf": "a silk scarf",
  /* v-studio-more-looks */
  "ring": "an elegant statement ring on the hand",
  "brooch": "a jewelled brooch pinned on the shoulder",
  "hairclip": "a decorative pearl hair clip",
  "cufflinks": "polished gold cufflinks on the shirt cuffs"
 },
 "eyes": {
  "blue": "a natural blue eye color",
  "green": "a natural green eye color",
  "hazel": "a natural hazel eye color",
  "grey": "a natural grey eye color",
  "whiteteeth": "naturally whiter, brighter teeth",
  "bigsmile": "a bright natural wide smile",
  "lashes": "fuller, longer natural eyelashes",
  "brows": "neatly shaped, defined eyebrows"
 },
 "body": {
  "athletic": "a lean athletic build",
  "muscular": "a muscular, well-defined build",
  "slim": "a slim, slender build",
  "toned": "a toned, fit build",
  "flatstomach": "a flat, toned stomach",
  "posture": "an upright, confident posture with shoulders back"
 },
 "background": {
  "studio": "a professional dark studio backdrop with soft golden light",
  "beach": "a sunny beach with sea and sky",
  "city": "a city skyline at night with bokeh lights",
  "office": "a modern bright office",
  "desert": "golden desert dunes at sunset",
  "garden": "a lush green garden",
  "luxury": "a luxurious palace interior with marble and chandeliers",
  "plainwhite": "a plain pure white background",
  /* v-studio-more-looks */
  "mosque": "a grand mosque courtyard with arches and soft evening light",
  "library": "a warm wood-panelled library wall of books",
  "snow": "a snowy mountain slope with soft falling snow",
  "cafe": "a cosy modern cafe interior with warm lamps softly blurred"
 },
 "palette": {
  "spring": "a warm light spring color palette (peach, coral, warm greens)",
  "summer": "a cool soft summer palette (lavender, dusty rose, soft blue)",
  "autumn": "a warm deep autumn palette (rust, olive, mustard, camel)",
  "winter": "a cool vivid winter palette (royal blue, emerald, black and white)",
  "warm": "warm earthy tones",
  "cool": "cool blue-based tones",
  "jewel": "rich jewel tones (emerald, sapphire, ruby)",
  "pastel": "soft pastel tones"
 },
 "seasons": {
  "eid": "a festive Eid look: a crisp new kandora or elegant dress with refined accessories, celebratory mood",
  "ramadan": "an elegant Ramadan evening look with a modest embroidered outfit and warm lantern-lit ambiance",
  "uaenational": "a UAE National Day look with the UAE flag colors (red, green, white, black) in scarf and accessories",
  "saudinational": "a Saudi National Day look with green and white accents and a Saudi flag scarf",
  "winterlook": "a stylish winter outfit with a coat and scarf",
  "summerlook": "a light, airy summer outfit",
  "graduationlook": "a graduation gown and cap in a celebratory setting",
  "party": "a glamorous evening party outfit"
 },
 "iconic": {
  "redcarpet": "a red-carpet gala look with a designer gown and a flash-photography backdrop",
  "oldmoney": "an old-money quiet-luxury look: tailored beige blazer, loafers, classic styling",
  "kpop": "a K-pop idol stage look with trendy styling and colorful stage lighting",
  "hollywood": "a classic 1950s Hollywood glamour look in black and white",
  "footballer": "a football star look in a professional kit on a stadium pitch",
  "royal": "a royal look with an ornate gown, a tiara and a palace setting",
  "streetstyle": "a trendy street-style look with sneakers and oversized outerwear on a city street",
  "bollywood": "a Bollywood glamour look with a vibrant embellished outfit",
  /* v-studio-more-looks */
  "businesscover": "a business-magazine cover look: a sharp tailored suit, arms crossed, confident lighting against a plain dark wall",
  "desertsafari": "a desert-safari look: light linen clothing and a wrapped scarf on golden dunes at sunset",
  "racing": "a motorsport look: a racing suit with sponsor patches, helmet under the arm, beside a race car in a pit lane",
  "chefstar": "a celebrity-chef look: a crisp white chef jacket in a bright professional kitchen"
 },
 "age": {
  "child": "a child around 7 years old",
  "teen": "a teenager around 16 years old",
  "twenties": "a young adult in their mid-twenties",
  "forties": "an adult in their mid-forties",
  "sixties": "a person in their mid-sixties",
  "elder": "an elderly person around 80 years old"
 }
};
const INSTR = {
 "idphoto": "Turn this photo into {s}. Keep the same person and face exactly, front-facing, neutral or slight smile, sharp focus. Output a single photorealistic image.",
 "hijab": "Change only the head covering and outfit to {s}. Keep the same person, face, pose and background exactly the same. Output a single photorealistic image.",
 "gulfmen": "Change only the outfit and headwear to {s}. Keep the same person, face, pose and background exactly the same. Output a single photorealistic image.",
 "menhair": "Change only the hair to {s}. Keep the same person, face, pose, clothing and background exactly the same, only alter the hairstyle. Output a single photorealistic image.",
 /* v-studio-variety: كان القالب يفرض «reddish-brown» على كلّ الخيارات — فالحنّاء البيضاء
    والخضاب الأسود يخرجان بنّيّين مثل غيرهما. اللون صار من الخيار نفسه. */
 /* v-studio-skin-lock: يُرسم على السطح الظاهر فعلًا في الصورة (كفّ أو ظهر يد) وعلى اليد نفسها */
 "henna": "Add {s}. Draw it onto the exact hands or feet already visible in this photo, on whichever surface is actually facing the camera (palm or back of the hand) — if the placement described above is not visible in this photo, adapt the same design naturally onto the surface that is — following the real curves, folds and perspective of that skin. Render it as a realistic dried henna stain in exactly the colour, pattern and placement described above — do not substitute any other colour or pattern. Fine crisp lines, high detail, matching the photo's own lighting and shadows. Keep the same hands and everything else in the photo exactly the same. Output a single photorealistic image.",
 "wedding": "Change the outfit, hair styling and makeup to {s}. Keep the same person, face and pose; the identity must stay clearly recognizable. Output a single photorealistic image.",
 "accessories": "Add {s} to the person, placed naturally and realistically. Keep everything else in the photo exactly the same. Output a single photorealistic image.",
 "eyes": "Apply {s}. Keep the same person, identity, pose and background exactly the same and fully realistic. Output a single photorealistic image.",
 "body": "Change the body shape to {s} while keeping the same face, identity, clothing style, pose and background; keep proportions realistic. Output a single photorealistic image.",
 "background": "Replace only the background with {s}, matching the lighting and perspective naturally. Keep the person, pose and outfit exactly the same. Output a single photorealistic image.",
 "palette": "Recolor the outfit and accessories in {s} that flatters the person's skin tone. Keep the same person, face, pose and background. Output a single photorealistic image.",
 "seasons": "Change the outfit and styling to {s}. Keep the same person, face and pose; the identity must stay clearly recognizable. Output a single photorealistic image.",
 "iconic": "Restyle the outfit, hair and setting into {s} while keeping the same person and face clearly recognizable. Output a single photorealistic image.",
 "age": "Change the apparent age of the person to {s} while keeping the same identity, features and expression. Output a single photorealistic image."
};
const FEATURE_INSTRUCTIONS = {};
Object.keys(INSTR).forEach((k) => { FEATURE_INSTRUCTIONS[k] = (style) => INSTR[k].replace('{s}', style); });
// جنس نموذج المعاينة لكل خيار (m/w) — لتوليد صور المعاينة من نماذجنا
const PREVIEW_SUBJECT = {
 "idphoto": {
  "__tab": "w",
  "white": "w",
  "blue": "w",
  "passport": "m",
  "residence": "w",
  "suit": "m",
  "kandoraformal": "m",
  "linkedin": "w",
  "graduation": "w"
 },
 "hijab": {
  "__tab": "w",
  "gulf": "w",
  "turkish": "w",
  "modern": "w",
  "shayla": "w",
  "colored": "w",
  "embroidered": "w",
  "sport": "w",
  "bridal": "w",
  "khaleejiwrap": "w",
  "layered": "w",
  "turban": "w",
  "silkprint": "w"
 },
 "gulfmen": {
  "__tab": "m",
  "whiteghutra": "m",
  "redshemagh": "m",
  "bwshemagh": "m",
  "cobra": "m",
  "hamdaniya": "m",
  "coloredkandora": "m",
  "qatari": "m",
  "kuwaiti": "m",
  "winterbisht": "m",
  "omanikummah": "m",
  "wintercoat": "m",
  "bahrainiattire": "m"
 },
 "menhair": {
  "__tab": "m",
  "fade": "m",
  "pompadour": "m",
  "curlytop": "m",
  "manbun": "m",
  "buzz": "m",
  "longmen": "m",
  "sidepart": "m",
  "undercut": "m",
  "quiff": "m",
  "afro": "m"
 },
 "henna": {
  "__tab": "w",
  "gulfhenna": "w",
  "indianhenna": "w",
  "sudanese": "w",
  "bridalhenna": "w",
  "minimal": "w",
  "feet": "w",
  "whitehenna": "w",
  "khidab": "w",
  "moroccan": "w",
  "cuff": "w",
  "fingertips": "w",
  "glitterhenna": "w",
  "emirati": "w",
  "najdi": "w",
  "kuwaitihenna": "w",
  "qatarihenna": "w",
  "omanihenna": "w",
  "bahrainihenna": "w",
  "yemenihenna": "w",
  "somalihenna": "w",
  "egyptianhenna": "w",
  "turkishhenna": "w",
  "persianhenna": "w",
  "pakistani": "w",
  "rajasthani": "w",
  "marwari": "w",
  "malayinai": "w",
  "tunisian": "w",
  "africanhenna": "w",
  "fusionhenna": "w",
  "palmfull": "w",
  "backhand": "w",
  "fingersonly": "w",
  "fingerbands": "w",
  "thumbmotif": "w",
  "knuckles": "w",
  "wristband": "w",
  "halfhand": "w",
  "forearmhenna": "w",
  "glovehenna": "w",
  "anklecuff": "w",
  "solefoot": "w",
  "bothhands": "w",
  "sidehand": "w",
  "shoulderhenna": "w",
  "neckhenna": "w",
  "armband": "w",
  "centrepalm": "w",
  "backfinger": "w",
  "mandalahenna": "w",
  "peacock": "w",
  "paisleyhenna": "w",
  "floralvine": "w",
  "rosegarden": "w",
  "lotushenna": "w",
  "jaali": "w",
  "checkerhenna": "w",
  "dotsgrid": "w",
  "chevronhenna": "w",
  "leaveshenna": "w",
  "butterfly": "w",
  "heartshenna": "w",
  "celestial": "w",
  "waveshenna": "w",
  "featherhenna": "w",
  "arabesque": "w",
  "calligraphyhenna": "w",
  "initialshenna": "w",
  "evileye": "w",
  "khamsa": "w",
  "palmtree": "w",
  "falconhenna": "m",
  "camelhenna": "w",
  "lacework": "w",
  "swirls": "w",
  "tribalhenna": "m",
  "abstractlines": "w",
  "botanical": "w",
  "bohohenna": "w",
  "darkmaroon": "w",
  "redblack": "w",
  "ombrehenna": "w",
  "glossgel": "w",
  "mattestain": "w",
  "crystalhenna": "w",
  "pearlhenna": "w",
  "silverglitter": "w",
  "goldleafhenna": "w",
  "neonhenna": "w",
  "pastelhenna": "w",
  "twotone": "w",
  "glowhenna": "w",
  "hennanightfull": "w",
  "engagementhenna": "w",
  "eidhenna": "w",
  "ramadanhenna": "w",
  "newbornhenna": "w",
  "graduationhenna": "w",
  "birthdayhenna": "w",
  "nationaldayhenna": "w",
  "guesthenna": "w",
  "festivalhenna": "w",
  "fineline": "w",
  "negativespace": "w",
  "tattoostyle": "w",
  "handharness": "w",
  "watchband": "w",
  "daintyhenna": "w",
  "geometricmodern": "w",
  "kidshenna": "w",
  "menssimple": "m",
  "bracelettassel": "w"
 },
 "wedding": {
  "__tab": "w",
  "bride": "w",
  "gulfbride": "w",
  "groom": "m",
  "gulfgroom": "m",
  "indianbride": "w",
  "moroccanbride": "w",
  "engagement": "w",
  "hennanight": "w",
  "milkah": "w",
  "receptionsuit": "m",
  "turkishbride": "w",
  "gardenparty": "w"
 },
 "accessories": {
  "__tab": "w",
  "watch": "m",
  "earrings": "w",
  "necklace": "w",
  "hat": "m",
  "cap": "m",
  "bag": "w",
  "bracelet": "w",
  "scarf": "w",
  "ring": "w",
  "brooch": "w",
  "hairclip": "w",
  "cufflinks": "m"
 },
 "eyes": {
  "__tab": "w",
  "blue": "w",
  "green": "w",
  "hazel": "w",
  "grey": "w",
  "whiteteeth": "w",
  "bigsmile": "w",
  "lashes": "w",
  "brows": "w"
 },
 "body": {
  "__tab": "m",
  "athletic": "m",
  "muscular": "m",
  "slim": "w",
  "toned": "w",
  "flatstomach": "m",
  "posture": "w"
 },
 "background": {
  "__tab": "w",
  "studio": "w",
  "beach": "w",
  "city": "m",
  "office": "m",
  "desert": "m",
  "garden": "w",
  "luxury": "w",
  "plainwhite": "w",
  "mosque": "m",
  "library": "m",
  "snow": "w",
  "cafe": "w"
 },
 "palette": {
  "__tab": "w",
  "spring": "w",
  "summer": "w",
  "autumn": "w",
  "winter": "w",
  "warm": "w",
  "cool": "w",
  "jewel": "w",
  "pastel": "w"
 },
 "seasons": {
  "__tab": "w",
  "eid": "m",
  "ramadan": "w",
  "uaenational": "m",
  "saudinational": "m",
  "winterlook": "w",
  "summerlook": "w",
  "graduationlook": "w",
  "party": "w"
 },
 "iconic": {
  "__tab": "w",
  "redcarpet": "w",
  "oldmoney": "m",
  "kpop": "w",
  "hollywood": "m",
  "footballer": "m",
  "royal": "w",
  "streetstyle": "m",
  "bollywood": "w",
  "businesscover": "m",
  "desertsafari": "m",
  "racing": "m",
  "chefstar": "w"
 },
 "age": {
  "__tab": "w",
  "child": "w",
  "teen": "w",
  "twenties": "w",
  "forties": "m",
  "sixties": "m",
  "elder": "m"
 }
};
// v-preview-fit: تأطير المعاينة بحيث تُظهر الميزة نفسها بوضوح (الحناء = يدان قريبتان، العيون = وجه قريب…)
const PREVIEW_FRAME = {
  idphoto: 'head-and-shoulders portrait, front-facing, neutral expression',
  hijab: 'upper-body portrait, the head covering fully visible',
  gulfmen: 'three-quarter portrait, the headwear and outfit fully visible',
  menhair: 'head-and-shoulders portrait, the hairstyle clearly visible and in focus',
  henna: 'close-up of the hands held toward the camera, palms and backs of hands filling the frame, the henna patterns sharp and clearly visible',
  wedding: 'full-body portrait, the wedding outfit fully visible',
  accessories: 'upper-body portrait, the accessory prominent and clearly visible',
  eyes: 'close-up face portrait, the eyes and smile in sharp focus and clearly visible',
  body: 'full-body standing portrait in fitted athletic clothing, the body shape clearly visible',
  background: 'three-quarter portrait with the background fully visible and in focus',
  palette: 'upper-body portrait, the outfit colors dominant and clearly visible',
  seasons: 'three-quarter portrait, the outfit and setting clearly visible',
  iconic: 'three-quarter portrait, the styling and setting clearly visible',
  age: 'head-and-shoulders portrait, the age clearly readable in the face',
};
const PREVIEW_FEATURE_NAME = {
  idphoto: 'the official ID-photo look', hijab: 'the hijab style', gulfmen: 'the Gulf attire', menhair: 'the haircut',
  henna: 'the henna design', wedding: 'the wedding look', accessories: 'the accessory', eyes: 'the eye color or smile',
  body: 'the body shape', background: 'the background', palette: 'the color palette', seasons: 'the occasion outfit',
  iconic: 'the iconic style', age: 'the apparent age',
};
module.exports = { STYLE_PROMPTS, FEATURE_INSTRUCTIONS, PREVIEW_SUBJECT, PREVIEW_FRAME, PREVIEW_FEATURE_NAME };
