// v-studio-more-looks (٢٨ سبتمبر ٢٠٢٦): أوصاف خيارات الميزات الأساسيّة لستوديو AI.
// كانت داخل studio-create.js، ونُقلت إلى ملفّ بيانات صرف بلا أسرار ولا قراءة بيئة
// كي يقرأها مولّد المعاينات (studio-preview) أيضًا — studio-create يقرأ الحصص
// (AUTH_SECRET) في نطاق الوحدة، فلا يصحّ تحميله من مسار المعاينة.
// كلّ وصف يذكر لونه وكثافته وموضعه ولمعته صراحةً: الأوصاف العامّة المتقاربة كانت
// تُخرج النتيجة نفسها لكلّ الخيارات (v-studio-variety).
'use strict';

const STYLE_TEXT = {
  hair: {
    black: 'a jet black hair colour with a glossy healthy shine, the same length and cut as now',
    brown: 'a natural chestnut brown hair colour with warm soft depth, the same length and cut as now',
    blonde: 'a golden blonde hair colour with warm honey depth at the roots, the same length and cut as now',
    red: 'a vivid auburn red hair colour with copper shine, the same length and cut as now',
    silver: 'a cool silver-grey hair colour with a smooth even tone, the same length and cut as now',
    colorful: 'a vivid multicolour fantasy hair colour: pink, blue and purple streaks blended through the lengths',
    ombre: 'an ombre colour fading from dark roots into light caramel ends with a soft blended transition',
    highlights: 'fine sun-kissed highlights threaded through the top layers over the natural base colour',
    platinum: 'an icy platinum blonde hair colour, almost white, with a cool ashy tone and no warmth',
    burgundy: 'a deep burgundy wine hair colour with rich red-violet depth',
    blue: 'a bold electric blue hair colour, saturated and even from root to tip',
    rose: 'a soft rose-gold pink hair colour with a pearly metallic sheen',
    curly: 'a voluminous curly hairstyle with defined bouncy spiral curls and lots of body',
    straight: 'a sleek poker-straight glossy hairstyle, smooth and flat with a mirror shine',
    waves: 'soft glamorous Hollywood waves, brushed out and shiny with a deep side parting',
    bob: 'a chic chin-length bob haircut with a blunt sharp line',
    pixie: 'a modern short pixie cut, textured on top with tapered sides',
    longlayers: 'long flowing layers that frame the face, with movement through the ends',
    /* v-studio-more-looks: دفعة الأشكال الجديدة */
    balayage: 'a hand-painted balayage: dark natural roots melting into sunlit caramel ends, soft and blended with no harsh line',
    copper: 'a bright copper-ginger hair colour, warm and metallic with a strong shine',
    ashbrown: 'a cool ash-brown hair colour, smoky and matte with no warm or red tones',
    honey: 'a warm honey-beige hair colour with light golden face-framing pieces',
    braids: 'neat braided hair: a crown of tight braids gathered back, smooth and shiny',
    updo: 'an elegant gathered updo (chignon) pinned at the back with a few soft loose strands at the front',
    bangs: 'the same hair length but with a full soft fringe (bangs) cut straight across the forehead just above the brows',
    shag: 'a modern shag cut: heavy choppy layers with curtain bangs and lived-in texture',
    jetwaves: 'deep glossy finger waves close to the head in a vintage 1930s style',
    darkroots: 'a lived-in look: deliberately dark shadowed roots blending into a lighter beige-blonde body',
  },
  nails: {
    red: 'classic glossy true-red nail polish on neatly filed medium-length nails',
    nude: 'a soft nude-beige nail polish with a natural glossy finish',
    black: 'an opaque matte black nail polish with a clean cuticle line',
    french: 'a classic French manicure: pale pink base with crisp white tips',
    pink: 'a soft baby-pink nail polish with a glossy finish',
    gold: 'a metallic gold glitter nail polish with dense fine sparkle',
    ombrenails: 'an ombre gradient manicure fading from a deep base at the cuticle into a pale tip',
    glitter: 'sparkling party nails: chunky multi-size glitter packed over a sheer base',
    mattegray: 'a matte greige (grey-beige) polish with a velvet shine-free finish',
    chrome: 'mirror chrome nails with a liquid-metal reflective silver finish',
    marble: 'white marble nail art with fine grey veining and a glossy top coat',
    artnails: 'delicate hand-painted floral nail art: tiny flowers and green leaves over a sheer base',
    /* v-studio-more-looks */
    coffin: 'long coffin-shaped (ballerina) nails in a glossy milky nude with sharp straight side walls',
    stiletto: 'long sharply pointed stiletto nails in a deep glossy red',
    squareshort: 'very short square-shaped natural nails in a clean sheer pink, neatly filed',
    almond: 'medium almond-shaped nails in a warm caramel-nude cream finish',
    babyboomer: 'baby-boomer nails: a seamless pink-to-white gradient with no visible smile line, high gloss',
    velvetnails: 'velvet (cat-magnet) nails: a deep plum base with a soft brushed light band running through each nail',
    auranails: 'aura nails: a glowing airbrushed halo of colour in the centre of each nail fading out to the edges',
    catseyenails: 'cat-eye magnetic nails: a dark shimmering base with a sharp bright light line across each nail',
    pearlnails: 'pearl nails: an iridescent white shimmer with a soft pearlescent colour shift',
    animalprint: 'hand-painted leopard-print nail art in brown and black over a nude base, on two accent nails only',
    khaleejinails: 'Gulf-bride nails: a nude base with fine gold foil flakes and a few tiny crystal stones near the cuticle',
    frenchcolor: 'a coloured French manicure: a milky base with bright tips in a bold colour and a thin gold line under them',
  },
  /* v-studio-variety (شكوى المالك ٢٨ سبتمبر «كلّهم نوع واحد»): الأوصاف كانت أسطرًا
     متقاربة (طبيعي/سوفت قلام/ديوي…) فتخرج بالوجه نفسه — كلّ خيار الآن بألوانه
     ودرجة تغطيته ولمعته صراحةً كي يُرى الفرق. */
  makeup: {
    natural: 'a light everyday "no-makeup" look: sheer skin tint only, soft brown mascara, groomed brows and a clear balm lip — no eyeshadow, no liner, no visible contour',
    glam: 'a full glamorous evening look: full-coverage foundation, sharply contoured and highlighted cheekbones, a dramatic cut-crease eyeshadow in warm bronze, black winged liner, dense false lashes and a glossy nude-beige lip',
    smokey: 'a dark smokey-eye look: charcoal-grey and black eyeshadow blended heavily all around the eye and along the lower lash line, smudged kohl, heavy lashes, with a deliberately bare matte nude lip and neutral cheeks',
    redlips: 'a classic red-lip look: a bold true-red matte lipstick with a sharply drawn lip line as the single focus, clean skin, a thin black liner flick and bare neutral eyeshadow',
    bridal: 'a soft bridal look: satin-finish skin, champagne and rose-gold shimmer on the lids, soft brown blended liner, long natural lashes, rosy blush and a muted pink-nude lip',
    softglam: 'a soft-glam look: warm taupe and peach eyeshadow lightly blended, thin brown liner, subtle highlighter on the high points, peach blush and a soft pink glossy lip — polished but far lighter than full glam',
    kohl: 'a striking Arabic kohl look: thick black kohl packed into the waterline and drawn well past the outer corner in a long dramatic wing, dark defined brows, bronzed skin and a deep brown-nude lip',
    dewy: 'a dewy fresh look: visibly wet-looking glowing skin with strong highlighter on the cheekbones, nose and cupid\'s bow, cream blush, glossy eyelids with no eyeshadow colour, and a clear shiny lip gloss',
    matte: 'a full matte look: completely shine-free velvet skin, matte warm-brown eyeshadow, matte terracotta blush and a matte brick-brown lipstick — no gloss, no shimmer and no highlighter anywhere',
    editorial: 'a bold editorial look: a vivid graphic eyeliner in a bright colour drawn in a sharp artistic shape over the lid, colour-blocked eyeshadow, bare glowing skin and a bold matching lip',
    coral: 'a fresh summer coral look: coral blush swept high on the cheeks, matching coral-peach eyeshadow, brown mascara and a juicy coral lip, with light natural skin coverage',
    goldeye: 'a gold shimmer eye look: metallic gold glitter packed on the centre of the lids, warm brown blending in the crease, soft black liner, golden highlighter and a warm beige nude lip',
    glassskin: 'a Korean glass-skin look: luminous poreless dewy skin, straight soft brows, pale pink blush on the cheeks and nose tip, minimal eye makeup and a gradient (ombre) lip darker in the centre',
    berry: 'a deep berry autumn look: a dark plum-berry lipstick, plum-toned smoked-out liner and berry blush, with matte skin and neutral brown eyeshadow',
    /* v-studio-more-looks */
    bronzed: 'a sun-bronzed look: warm bronzer sculpting the cheeks, temples and nose, golden shimmer on the high points, bronze eyeshadow washed over the lids and a warm caramel gloss',
    cutcrease: 'a sharp cut-crease look: a clean carved line above the lid with a light shimmer shade inside it and a deep matte shade above, black winged liner and full false lashes',
    siren: 'a siren-eye look: eyeliner drawn as a long sharp line stretching far past the outer corner and lifting the eye, a smoked-out lower line, bare lids otherwise and a glossy nude lip',
    dolleyes: 'a doll-eye look: round wide-open eyes with white liner on the waterline, individual spiky lashes on the top and bottom, pale shimmer on the lid centre and a pink cream lip',
    latte: 'a latte look: everything in warm coffee tones — milky-brown eyeshadow blended all over the lid, brown liner, mocha blush and a brown-lined nude lip',
    cherry: 'a cherry look: a glossy deep cherry-red lip with a matching soft cherry blush pressed on the cheeks, clean glowing skin and bare brown eyeshadow',
    festival: 'a festival look: chunky face glitter and rhinestones scattered along the cheekbones and lid corners, bright shimmer eyeshadow and a clear high-shine lip',
    softmatteGulf: 'a Gulf soirée look: heavy black kohl and long lashes, a strongly sculpted contour, matte full-coverage skin, gold shimmer on the inner corners and a muted rosewood matte lip',
  },
  beard: {
    full: 'a full thick well-groomed beard with a defined neckline and a trimmed moustache',
    stubble: 'light designer stubble, a few days\' growth, evenly trimmed and sharp at the cheek line',
    mustache: 'a neat moustache only, with the cheeks and chin cleanly shaved',
    goatee: 'a neat goatee: hair on the chin and around the mouth only, cheeks shaved',
    clean: 'a completely clean-shaven face with smooth skin and no stubble shadow',
    boxed: 'a short boxed beard with sharply edged cheek and neck lines',
    vandyke: 'a Van Dyke beard: a pointed chin beard with a moustache detached from it',
    faded: 'a beard faded into the haircut at the sideburns, dense at the chin',
    longbeard: 'a thick long beard reaching the chest, well-combed and groomed',
    anchor: 'an anchor beard: a pointed chin strip with a moustache, following the jawline',
    /* v-studio-more-looks */
    ducktail: 'a ducktail beard: full on the cheeks and tapering to a point below the chin',
    chinstrap: 'a thin chinstrap beard tracing the jawline, with the chin and cheeks otherwise shaved',
    circlebeard: 'a circle beard: a rounded moustache joined to a rounded chin beard',
    mutton: 'wide mutton-chop sideburns down the cheeks with a shaved chin',
    greybeard: 'a distinguished salt-and-pepper grey beard, full and neatly shaped',
    shapedbeard: 'a barber-shaped beard with razor-sharp edges on the cheek and neck lines and a subtle fade at the sideburns',
  },
  skin: {
    subtle: 'subtle natural skin smoothing that keeps realistic skin texture and visible pores',
    glow: 'a healthy natural glow with an even skin tone and soft light on the cheekbones',
    circles: 'reduced dark circles under the eyes for a rested, refreshed look',
    tan: 'a healthy sun-kissed golden tan skin tone, even across the face and neck',
    matteskin: 'a shine-free matte refined skin finish with no oily highlights',
    freckles: 'charming natural light freckles scattered over the nose and cheeks',
    /* v-studio-more-looks */
    poreless: 'a smooth poreless finish on the cheeks and nose while keeping the skin looking real, not plastic',
    acneclear: 'clear skin: active blemishes and spots removed, redness calmed, natural texture kept',
    scarfree: 'faded old acne scars and marks, evened out into the surrounding skin tone',
    hydrated: 'plump, well-hydrated skin with fine dryness lines softened and a fresh supple surface',
    evenTone: 'an even skin tone with pigmentation patches and redness balanced out naturally',
    softfilter: 'a soft-focus finish like fine studio diffusion: gentle on texture, still clearly a real photograph',
  },
  glasses: {
    sunglasses: 'classic black rectangular sunglasses with dark lenses',
    round: 'round vintage-style metal glasses with clear lenses',
    catseye: 'cat-eye shaped glasses with lifted outer corners',
    aviator: 'aviator glasses with a thin metal frame and teardrop lenses',
    rimless: 'thin rimless glasses with barely visible edges',
    wayfarer: 'classic thick-framed wayfarer glasses',
    oversized: 'fashionable oversized frame glasses covering the brows',
    sportglasses: 'sleek wraparound sport sunglasses with mirrored lenses',
    goldframe: 'luxury thin gold-frame glasses with clear lenses',
    retroglasses: 'retro 70s glasses with warm brown tinted lenses',
    hexagon: 'modern hexagonal thin-metal frame glasses',
    clearframe: 'trendy clear transparent acetate frame glasses',
    /* v-studio-more-looks */
    browline: 'browline glasses: a thick top bar with a thin metal lower rim',
    octagon: 'octagonal thin gold-rim glasses with clear lenses',
    halfrim: 'half-rim glasses with the frame on the top half only',
    bluelight: 'modern slim computer glasses with a faint blue-violet lens reflection',
    mirrored: 'mirrored sunglasses with a bright reflective silver-blue lens',
    tinyframe: 'tiny narrow trend sunglasses with small dark oval lenses',
  },
  tattoo: {
    sleeve: 'a detailed full arm sleeve tattoo in black and grey shading',
    wrist: 'a small delicate fine-line wrist tattoo',
    back: 'a large detailed back-piece tattoo with heavy shading',
    tribal: 'a bold black tribal tattoo with thick curved bands',
    geometric: 'a fine-line geometric tattoo of interlocking shapes',
    minimalline: 'a tiny minimalist single-line tattoo',
    arabictattoo: 'an elegant Arabic calligraphy tattoo in a flowing script',
    floraltattoo: 'a detailed floral botanical tattoo with fine stippled shading',
    custom: 'a custom tattoo design as described',
    /* v-studio-more-looks */
    japanese: 'a Japanese irezumi tattoo: waves, koi and peony in bold outlines with dense colour',
    blackwork: 'a heavy blackwork tattoo: large areas of solid black with sharp negative-space shapes',
    watercolortattoo: 'a watercolour tattoo with soft colour splashes and paint drips and no black outline',
    necktattoo: 'a small tattoo on the side of the neck, fine-line and delicate',
    chesttattoo: 'a symmetrical chest-piece tattoo spreading across both collarbones',
    ankletattoo: 'a fine tattoo band around the ankle',
    dotwork: 'a dotwork (stippled) mandala tattoo built entirely from tiny black dots',
  },
  anime: {
    classic: 'a classic Japanese anime art style illustration with cel shading and clean line art',
    chibi: 'a cute chibi cartoon style illustration with a huge head and tiny body',
    ghibli: 'a Studio Ghibli-inspired hand-painted anime style with soft watercolour backgrounds',
    cyberpunk: 'a cyberpunk anime art style with neon accents and a rainy night city behind',
    manga: 'a black and white manga ink illustration with screentones and hatching',
    shonenstudio: 'a dynamic shonen action anime style with speed lines and glowing energy',
    kawaii: 'a cute kawaii pastel anime style with sparkles and soft pink tones',
    webtoon: 'a clean modern webtoon comic style with soft gradients and thin line art',
    retro90s: 'a nostalgic 1990s cel anime style with grainy film texture and muted colours',
    /* v-studio-more-looks */
    seinen: 'a mature seinen anime style: realistic proportions, detailed rendering and moody lighting',
    mecha: 'a mecha anime style: the person in a pilot suit with a giant robot looming behind',
    isekai: 'an isekai fantasy anime style: adventurer clothing, a magic aura and a fantasy landscape behind',
    magicalgirl: 'a magical-girl anime style: a frilly transformation outfit, ribbons, sparkles and a glowing wand',
    cinematicanime: 'a cinematic anime-film style: painterly backgrounds, film-grade lighting and a wide movie frame feel',
    sportanime: 'a sports anime style: a team uniform, sweat and motion, a stadium and dramatic angle',
    shojo: 'a shojo anime style: huge sparkling eyes, flower petals in the air and soft pastel screentones',
  },
  heritage: {
    kandora: 'a traditional Gulf men\'s kandora (dishdasha) with a matching ghutra headscarf and agal',
    bisht: 'a luxurious traditional Gulf bisht cloak with gold trim worn over a white kandora',
    abaya: 'an elegant traditional women\'s black abaya with a matching sheila headscarf',
    embroidered: 'a richly embroidered traditional Gulf women\'s dress (thobe nashal) with gold detailing',
    saudi: 'a traditional Saudi men\'s thobe with a red-and-white shemagh headscarf',
    emirati: 'a traditional Emirati women\'s kaftan with delicate hand embroidery',
    omani: 'a traditional Omani men\'s dishdasha with an embroidered kummah cap',
    saudimen2: 'a Saudi winter bisht worn over a thobe with a red shemagh, a stately look',
    moroccanher: 'a Moroccan djellaba with a hood and fine stitching',
    palestinian: 'a Palestinian embroidered thobe with traditional tatreez patterns',
    /* v-studio-more-looks */
    kuwaitiher: 'a traditional Kuwaiti daraa: a loose embroidered dress with gold zari trim at the neckline and cuffs',
    qatarither: 'a traditional Qatari thobe al-nashal in a deep jewel tone with heavy gold thread embroidery',
    bahrainiher: 'a traditional Bahraini dress with fine pearl-inspired embroidery and a light sheila',
    omaniwomen: 'traditional Omani women\'s dress: a brightly coloured embroidered tunic with sirwal trousers and a lihaf headscarf',
    yemeni: 'a traditional Yemeni look: a patterned wrap (maawaz) with an embroidered belt, or a Sanaani embroidered dress',
    egyptian: 'a traditional Egyptian galabeya with a woven sash and simple embroidery at the neck',
    sudanesedress: 'a traditional Sudanese look: a colourful wrapped thobe for women, or a white jalabiya with an imma turban for men',
    levantine: 'a traditional Levantine look: a cross-stitch embroidered thobe for women, or a sherwal with a vest and a hatta for men',
  },
};

/* ───── وصف المعاينة للميزات الأساسيّة (نفس نظام studio-more للميزات الـ١٤):
   التأطير يجب أن يُظهر الميزة نفسها — صور المكياج الجاهزة كانت جسمًا كاملًا
   فبدت الخيارات العشرة صورة واحدة. ───── */
const PREVIEW_FRAME = {
  hair: 'head-and-shoulders portrait, the hair colour and cut fully visible and in focus',
  nails: 'close-up of one hand raised near the face, the fingernails filling much of the frame and sharply in focus',
  makeup: 'tight close-up beauty portrait of the face only, the eyes and lips sharply in focus, the makeup clearly readable',
  beard: 'head-and-shoulders portrait, the facial hair sharply in focus',
  skin: 'tight close-up beauty portrait of the face, the skin texture and finish clearly visible',
  glasses: 'head-and-shoulders portrait, the glasses front-facing and clearly visible',
  tattoo: 'close-up of the tattooed area, the tattoo artwork sharp and clearly visible',
  anime: 'upper-body character illustration, the art style clearly readable',
  heritage: 'three-quarter portrait, the traditional outfit and headwear fully visible',
};
const PREVIEW_FEATURE_NAME = {
  hair: 'the hair colour or hairstyle', nails: 'the nail design', makeup: 'the makeup look',
  beard: 'the beard style', skin: 'the skin finish', glasses: 'the glasses',
  tattoo: 'the tattoo', anime: 'the art style', heritage: 'the heritage outfit',
};
/* جنس نموذج المعاينة: الافتراضيّ للميزة في __tab، والاستثناءات بالخيار */
const PREVIEW_SUBJECT = {
  hair: { __tab: 'w' },
  nails: { __tab: 'w' },
  makeup: { __tab: 'w' },
  beard: { __tab: 'm' },
  skin: { __tab: 'w' },
  glasses: { __tab: 'w', aviator: 'm', wayfarer: 'm', sportglasses: 'm', browline: 'm', mirrored: 'm', bluelight: 'm' },
  tattoo: { __tab: 'm', wrist: 'w', minimalline: 'w', floraltattoo: 'w', ankletattoo: 'w', necktattoo: 'w' },
  anime: { __tab: 'w', shonenstudio: 'm', mecha: 'm', seinen: 'm', sportanime: 'm', isekai: 'm' },
  heritage: {
    __tab: 'm', kandora: 'm', bisht: 'm', saudi: 'm', omani: 'm', saudimen2: 'm', moroccanher: 'm',
    abaya: 'w', embroidered: 'w', emirati: 'w', palestinian: 'w', kuwaitiher: 'w', qatarither: 'w',
    bahrainiher: 'w', omaniwomen: 'w', yemeni: 'm', egyptian: 'm', sudanesedress: 'w', levantine: 'w',
  },
};

module.exports = { STYLE_TEXT, PREVIEW_FRAME, PREVIEW_FEATURE_NAME, PREVIEW_SUBJECT };
