// v-studio-more-looks (٢٨ سبتمبر ٢٠٢٦): أوصاف خيارات الميزات الأساسيّة لستوديو AI.
// كانت داخل studio-create.js، ونُقلت إلى ملفّ بيانات صرف بلا أسرار ولا قراءة بيئة
// كي يقرأها مولّد المعاينات (studio-preview) أيضًا — studio-create يقرأ الحصص
// (AUTH_SECRET) في نطاق الوحدة، فلا يصحّ تحميله من مسار المعاينة.
// كلّ وصف يذكر لونه وكثافته وموضعه ولمعته صراحةً: الأوصاف العامّة المتقاربة كانت
// تُخرج النتيجة نفسها لكلّ الخيارات (v-studio-variety).
'use strict';

const STYLE_TEXT = {
  hair: {
    black: 'a jet black hair colour with a glossy healthy shine, the same length and cut as now',
    brown: 'a natural chestnut brown hair colour with warm soft depth, the same length and cut as now',
    blonde: 'a golden blonde hair colour with warm honey depth at the roots, the same length and cut as now',
    red: 'a vivid auburn red hair colour with copper shine, the same length and cut as now',
    silver: 'a cool silver-grey hair colour with a smooth even tone, the same length and cut as now',
    colorful: 'a vivid multicolour fantasy hair colour: pink, blue and purple streaks blended through the lengths',
    ombre: 'an ombre colour fading from dark roots into light caramel ends with a soft blended transition',
    highlights: 'fine sun-kissed highlights threaded through the top layers over the natural base colour',
    platinum: 'an icy platinum blonde hair colour, almost white, with a cool ashy tone and no warmth',
    burgundy: 'a deep burgundy wine hair colour with rich red-violet depth',
    blue: 'a bold electric blue hair colour, saturated and even from root to tip',
    rose: 'a soft rose-gold pink hair colour with a pearly metallic sheen',
    curly: 'a voluminous curly hairstyle with defined bouncy spiral curls and lots of body',
    straight: 'a sleek poker-straight glossy hairstyle, smooth and flat with a mirror shine',
    waves: 'soft glamorous Hollywood waves, brushed out and shiny with a deep side parting',
    bob: 'a chic chin-length bob haircut with a blunt sharp line',
    pixie: 'a modern short pixie cut, textured on top with tapered sides',
    longlayers: 'long flowing layers that frame the face, with movement through the ends',
    /* v-studio-more-looks: دفعة الأشكال الجديدة */
    balayage: 'a hand-painted balayage: dark natural roots melting into sunlit caramel ends, soft and blended with no harsh line',
    copper: 'a bright copper-ginger hair colour, warm and metallic with a strong shine',
    ashbrown: 'a cool ash-brown hair colour, smoky and matte with no warm or red tones',
    honey: 'a warm honey-beige hair colour with light golden face-framing pieces',
    braids: 'neat braided hair: a crown of tight braids gathered back, smooth and shiny',
    updo: 'an elegant gathered updo (chignon) pinned at the back with a few soft loose strands at the front',
    bangs: 'the same hair length but with a full soft fringe (bangs) cut straight across the forehead just above the brows',
    shag: 'a modern shag cut: heavy choppy layers with curtain bangs and lived-in texture',
    jetwaves: 'deep glossy finger waves close to the head in a vintage 1930s style',
    darkroots: 'a lived-in look: deliberately dark shadowed roots blending into a lighter beige-blonde body',
    /* v-studio-100: دفعة الـ١٠٠ شكل (طلب المالك «على الأقلّ ١٠٠ نوع وشكل») */
    blueblack: 'a blue-black hair colour with a cool glossy sheen',
    espresso: 'a deep espresso-brown colour, almost black in shade but warm in the light',
    mocha: 'a mid mocha-brown colour with balanced neutral tones',
    caramelhair: 'warm caramel-brown with lighter ribbons through the mid-lengths',
    toffee: 'a rich toffee-brown with golden warmth at the ends',
    beigeblonde: 'a soft beige blonde with no brassiness, even from root to tip',
    butterblonde: 'a warm buttery blonde with soft golden depth',
    strawberryblonde: 'a strawberry blonde: light blonde with a clear rosy-red cast',
    gingerhair: 'a natural ginger red with freckled warmth and soft shine',
    mahogany: 'a deep mahogany brown-red with rich violet undertones',
    cherryred: 'a bright cherry-red colour, saturated and glossy',
    plumhair: 'a deep plum-purple colour that reads dark until the light hits it',
    lavenderhair: 'a pastel lavender colour, soft and evenly toned',
    pastelpink: 'a pastel pink colour with a milky finish',
    peachhair: 'a soft peach colour blending pink and apricot tones',
    minthair: 'a pastel mint-green colour with a cool tone',
    tealhair: 'a deep teal blue-green colour, saturated and glossy',
    navyhair: 'a dark navy-blue colour that shows its blue only in bright light',
    emeraldhair: 'a jewel emerald-green colour with deep saturation',
    charcoalhair: 'a smoky charcoal-grey colour, cool and matte',
    sunsetombre: 'a sunset ombré fading from deep red roots through orange into golden ends',
    moneypiece: 'bright face-framing money-piece highlights against the natural base',
    babylights: 'ultra-fine babylights woven throughout for a naturally sun-lightened look',
    lowlights: 'darker lowlights woven through to add depth and dimension',
    chunky90s: 'thick contrasting chunky highlights in a deliberate 1990s style',
    peekaboo: 'a hidden peekaboo colour underneath that shows only when the hair moves',
    underlayer: 'the whole under-layer dyed a contrasting bright colour beneath a natural top',
    splitdye: 'a split dye: one half of the head one colour, the other half another, divided down the middle',
    ecaille: 'tortoiseshell (ecaille) colour: soft blended browns, caramels and honey tones',
    bronde: 'bronde: a blend of brown and blonde kept soft and low contrast',
    butterflycut: 'a butterfly cut: short face-framing layers over long lengths for big volume',
    wolfcut: 'a wolf cut: heavy choppy layers, shaggy crown and wispy ends',
    bluntcut: 'a blunt one-length cut with a heavy straight line at the ends',
    lob: 'a collarbone-length lob with soft movement at the ends',
    frenchbob: 'a chin-length French bob paired with a soft fringe',
    curtainbangs: 'long curtain bangs parted in the middle and sweeping to each side',
    babybangs: 'very short baby bangs cut high above the brows',
    sidebangs: 'long side-swept bangs falling across one eyebrow',
    curlybob: 'a curly bob with defined springy curls at chin length',
    mullet: 'a modern mullet: short on top and the sides with length left at the back',
    feathered: 'feathered layers flicked away from the face in a soft 70s shape',
    beachwaves: 'loose undone beach waves with a matte texture',
    deepwaves: 'deep uniform S-waves running the full length of the hair',
    tightcurls: 'tight defined curls with high definition and volume',
    afrohair: 'a full rounded afro with even natural texture',
    coils: 'tight natural coils with defined springs and a soft sheen',
    crimped: 'crimped hair with fine zigzag texture throughout',
    sleekbun: 'a sleek low bun with the hair pulled perfectly flat and shiny',
    highpony: 'a high sleek ponytail pulled tight at the crown',
    lowpony: 'a low ponytail tied at the nape with a soft middle parting',
    bubblebraid: 'a bubble ponytail sectioned into rounded puffs with fine elastics',
    fishtail: 'a fishtail braid with fine interlocking strands, softly pulled out',
    dutchbraids: 'two raised Dutch braids running from the hairline to the nape',
    halobraid: 'a halo braid wrapped around the head like a crown',
    spacebuns: 'two high space buns with a few loose strands left down',
    topknot: 'a high top knot with smooth sides',
    messybun: 'a deliberately messy bun with soft pieces falling around the face',
    clawclip: 'hair twisted up into a claw clip with relaxed strands escaping',
    halfup: 'a half-up half-down style with volume at the crown',
    wetlook: 'a slicked wet-look finish with the hair combed back and glossy',
    blowout: 'a big bouncy salon blowout with rounded volume at the ends',
    bouffant: 'a 1960s bouffant with a lifted, back-combed crown',
    victoryrolls: '1940s victory rolls pinned at the front with smooth lengths behind',
    slickedback: 'hair slicked straight back off the face with a glossy finish',
    sidepart2: 'a deep side part with the hair sweeping across the forehead',
    middlepart: 'a clean centre part with straight smooth lengths on both sides',
    hairbraidsgulf: 'many fine braids gathered back in a traditional Gulf style',
    cornrows: 'neat cornrows braided close to the scalp in straight rows',
    locs: 'mature well-formed locs of even thickness',
    twistout: 'a twist-out with soft defined waves and lots of body',
    perm: 'a soft permed texture with uniform loose curls throughout',
    keratin: 'a keratin-smoothed finish: sleek, frizz-free and softly shiny',
    volumeshort: 'short hair styled for maximum lift and volume at the roots',
    thinning: 'visibly fuller, denser hair with the same colour and cut',
    greyblend: 'grey hairs softly blended into the natural colour rather than fully covered',
    naturalgrey: 'the natural silver-grey worn deliberately, toned bright and glossy',
  },
  nails: {
    red: 'classic glossy true-red nail polish on neatly filed medium-length nails',
    nude: 'a soft nude-beige nail polish with a natural glossy finish',
    black: 'an opaque matte black nail polish with a clean cuticle line',
    french: 'a classic French manicure: pale pink base with crisp white tips',
    pink: 'a soft baby-pink nail polish with a glossy finish',
    gold: 'a metallic gold glitter nail polish with dense fine sparkle',
    ombrenails: 'an ombre gradient manicure fading from a deep base at the cuticle into a pale tip',
    glitter: 'sparkling party nails: chunky multi-size glitter packed over a sheer base',
    mattegray: 'a matte greige (grey-beige) polish with a velvet shine-free finish',
    chrome: 'mirror chrome nails with a liquid-metal reflective silver finish',
    marble: 'white marble nail art with fine grey veining and a glossy top coat',
    artnails: 'delicate hand-painted floral nail art: tiny flowers and green leaves over a sheer base',
    /* v-studio-more-looks */
    coffin: 'long coffin-shaped (ballerina) nails in a glossy milky nude with sharp straight side walls',
    stiletto: 'long sharply pointed stiletto nails in a deep glossy red',
    squareshort: 'very short square-shaped natural nails in a clean sheer pink, neatly filed',
    almond: 'medium almond-shaped nails in a warm caramel-nude cream finish',
    babyboomer: 'baby-boomer nails: a seamless pink-to-white gradient with no visible smile line, high gloss',
    velvetnails: 'velvet (cat-magnet) nails: a deep plum base with a soft brushed light band running through each nail',
    auranails: 'aura nails: a glowing airbrushed halo of colour in the centre of each nail fading out to the edges',
    catseyenails: 'cat-eye magnetic nails: a dark shimmering base with a sharp bright light line across each nail',
    pearlnails: 'pearl nails: an iridescent white shimmer with a soft pearlescent colour shift',
    animalprint: 'hand-painted leopard-print nail art in brown and black over a nude base, on two accent nails only',
    khaleejinails: 'Gulf-bride nails: a nude base with fine gold foil flakes and a few tiny crystal stones near the cuticle',
    frenchcolor: 'a coloured French manicure: a milky base with bright tips in a bold colour and a thin gold line under them',
    /* v-studio-100: دفعة الـ١٠٠ شكل (طلب المالك «على الأقلّ ١٠٠ نوع وشكل») */
    oval: 'neatly filed oval nails in a sheer milky pink with a high-gloss finish',
    squoval: 'squoval nails — square with softened corners — in a warm nude cream',
    ballerina: 'long ballerina-tapered nails in a glossy cool-toned beige',
    flarenails: 'retro flare (duck) nails widening at the tip, in a bright glossy red',
    lipsticknails: 'lipstick-shaped nails cut on a slant, in a deep glossy plum',
    extrashort: 'very short bitten-length nails tidied and painted in a clean sheer nude',
    xlnails: 'extra-long sculpted nails in a glossy jet black with sharp square tips',
    whitenails: 'opaque milky-white polish with a soft glossy finish',
    navynails: 'deep navy-blue polish with a rich glossy finish',
    emeraldnails: 'jewel-toned emerald green polish, deep and glossy',
    lilacnails: 'soft lilac polish with a creamy opaque finish',
    mintnails: 'pale mint-green polish with a smooth cream finish',
    peachnails: 'warm peach polish with a soft pearly sheen',
    burgundynails: 'deep burgundy wine polish with a mirror gloss',
    taupenails: 'muted taupe polish, the quiet everyday neutral',
    cherrynails: 'glossy cherry-red polish with a slight blue undertone',
    coralnails: 'bright coral polish, fresh and summery',
    skybluenails: 'pale sky-blue polish with a clean cream finish',
    mustardnails: 'warm mustard-yellow polish with a matte-leaning cream finish',
    chocolatenails: 'rich chocolate-brown polish with a glossy finish',
    rosegoldnails: 'metallic rose-gold polish with a fine reflective shimmer',
    bronzenails: 'metallic bronze polish with a warm foil-like shine',
    tealnails: 'deep teal polish with a glassy finish',
    holographic: 'holographic nails shifting through rainbow colours as the light moves',
    jellynails: 'sheer jelly nails in a translucent candy tint, glassy and see-through',
    glazeddonut: 'glazed-donut nails: a milky base veiled in fine pearl chrome shimmer',
    sugarnails: 'textured sugar nails with a fine grainy sparkle over a soft colour',
    foilnails: 'torn metallic foil flakes scattered over a neutral base',
    shimmernails: 'a sheer base packed with fine shimmer that glows rather than sparkles',
    microfrench: 'a micro French manicure with a hair-thin white line at the very tip',
    doublefrench: 'a double French with two stacked tip lines in contrasting colours',
    vfrench: 'a V-shaped French tip pointing down towards the cuticle',
    diagonalfrench: 'a diagonal French tip cut across each nail at a sharp angle',
    reversefrench: 'a reverse French: the colour arc sits at the cuticle, the tip stays bare',
    halfmoon: 'a half-moon manicure with a bare crescent at the base of each nail',
    swirlnails: 'hand-painted swirling ribbons of two colours curling across each nail',
    checkernails: 'a checkerboard grid painted across the nails in two contrasting colours',
    polkadots: 'evenly spaced polka dots over a soft pastel base',
    stripesnails: 'fine parallel stripes running down the length of each nail',
    plaidnails: 'a plaid tartan pattern hand-painted in fine crossing lines',
    zebranails: 'black zebra stripes over a stark white base',
    cownails: 'irregular cow-print patches in black over a white base',
    flamesnails: 'hot-rod flames licking up from the tips in orange and red',
    smileynails: 'tiny smiley faces dotted on two accent nails over a plain base',
    starsnails: 'scattered gold stars over a deep midnight base',
    heartsnails: 'tiny hearts painted near the cuticle over a sheer pink base',
    evileyenails: 'a single evil-eye motif on one accent nail, plain colour on the rest',
    butterflynails: 'delicate butterfly wings painted across two nails in soft colours',
    fruitnails: 'tiny hand-painted strawberries and cherries over a milky base',
    floralnails2: 'fine hand-painted roses with green leaves over a nude base',
    tortoiseshell: 'tortoiseshell nails: amber and dark brown blotches blended in a glossy finish',
    watercolornails: 'soft watercolour washes bleeding into one another across the nail',
    negativenails: 'negative-space art: painted shapes leaving bare nail showing between them',
    lacenails: 'fine white lace patterns painted over a sheer blush base',
    abstractnails: 'free abstract brush strokes in two or three colours over a clear base',
    auroranails: 'aurora nails: a dark base with iridescent flakes glowing like northern lights',
    crystalnails: 'crystal stones clustered near the cuticle of two accent nails',
    pearlnails2: 'small 3D pearls placed along the cuticle line of each nail',
    flowers3d: 'raised 3D sculpted flowers built on two accent nails',
    charmnails: 'tiny metal charms fixed onto one accent nail over a glossy base',
    chromebutterfly: 'chrome-powder artwork rubbed into a design over a dark base',
    bridalnails: 'bridal nails: a milky base with fine gold detail and a few pearls',
    eidnails: 'festive Eid nails: a deep base with gold crescents on two accent nails',
    ramadannails: 'quiet Ramadan nails: a muted base with a fine gold lantern outline',
    nationalnails: 'national-day nails in red, green, white and black across the set',
    graduationnails: 'graduation nails: a clean base with a tiny cap motif on one nail',
    partynails: 'party nails: dense glitter on two nails and a deep colour on the rest',
    officenails: 'office-appropriate short nude nails with a clean glossy finish',
    gelnatural: 'a natural gel overlay on the own nails: strong, shiny and colourless',
    builderclear: 'a clear builder-gel finish that thickens and smooths the natural nail',
    khaleejibride: 'Gulf luxe nails: a nude base with gold foil, fine crystals and a pearl accent',
    minimalline: 'one fine gold line drawn across an otherwise bare, glossy nail',
    duotone: 'each nail split into two flat colours by a clean straight line',
    accentonly: 'a plain nude set with one boldly patterned accent nail',
    gradientglitter: 'glitter faded from dense at the tip to bare at the cuticle',
    velvetred: 'red velvet nails: a deep red magnetic finish with a soft brushed glow',
    snownails: 'fine white snowflakes painted over an icy blue shimmer base',
  },
  /* v-studio-variety (شكوى المالك ٢٨ سبتمبر «كلّهم نوع واحد»): الأوصاف كانت أسطرًا
     متقاربة (طبيعي/سوفت قلام/ديوي…) فتخرج بالوجه نفسه — كلّ خيار الآن بألوانه
     ودرجة تغطيته ولمعته صراحةً كي يُرى الفرق. */
  makeup: {
    natural: 'a light everyday "no-makeup" look: sheer skin tint only, soft brown mascara, groomed brows and a clear balm lip — no eyeshadow, no liner, no visible contour',
    glam: 'a full glamorous evening look: full-coverage foundation, sharply contoured and highlighted cheekbones, a dramatic cut-crease eyeshadow in warm bronze, black winged liner, dense false lashes and a glossy nude-beige lip',
    smokey: 'a dark smokey-eye look: charcoal-grey and black eyeshadow blended heavily all around the eye and along the lower lash line, smudged kohl, heavy lashes, with a deliberately bare matte nude lip and neutral cheeks',
    redlips: 'a classic red-lip look: a bold true-red matte lipstick with a sharply drawn lip line as the single focus, clean skin, a thin black liner flick and bare neutral eyeshadow',
    bridal: 'a soft bridal look: satin-finish skin, champagne and rose-gold shimmer on the lids, soft brown blended liner, long natural lashes, rosy blush and a muted pink-nude lip',
    softglam: 'a soft-glam look: warm taupe and peach eyeshadow lightly blended, thin brown liner, subtle highlighter on the high points, peach blush and a soft pink glossy lip — polished but far lighter than full glam',
    kohl: 'a striking Arabic kohl look: thick black kohl packed into the waterline and drawn well past the outer corner in a long dramatic wing, dark defined brows, bronzed skin and a deep brown-nude lip',
    dewy: 'a dewy fresh look: visibly wet-looking glowing skin with strong highlighter on the cheekbones, nose and cupid\'s bow, cream blush, glossy eyelids with no eyeshadow colour, and a clear shiny lip gloss',
    matte: 'a full matte look: completely shine-free velvet skin, matte warm-brown eyeshadow, matte terracotta blush and a matte brick-brown lipstick — no gloss, no shimmer and no highlighter anywhere',
    editorial: 'a bold editorial look: a vivid graphic eyeliner in a bright colour drawn in a sharp artistic shape over the lid, colour-blocked eyeshadow, bare glowing skin and a bold matching lip',
    coral: 'a fresh summer coral look: coral blush swept high on the cheeks, matching coral-peach eyeshadow, brown mascara and a juicy coral lip, with light natural skin coverage',
    goldeye: 'a gold shimmer eye look: metallic gold glitter packed on the centre of the lids, warm brown blending in the crease, soft black liner, golden highlighter and a warm beige nude lip',
    glassskin: 'a Korean glass-skin look: luminous poreless dewy skin, straight soft brows, pale pink blush on the cheeks and nose tip, minimal eye makeup and a gradient (ombre) lip darker in the centre',
    berry: 'a deep berry autumn look: a dark plum-berry lipstick, plum-toned smoked-out liner and berry blush, with matte skin and neutral brown eyeshadow',
    /* v-studio-more-looks */
    bronzed: 'a sun-bronzed look: warm bronzer sculpting the cheeks, temples and nose, golden shimmer on the high points, bronze eyeshadow washed over the lids and a warm caramel gloss',
    cutcrease: 'a sharp cut-crease look: a clean carved line above the lid with a light shimmer shade inside it and a deep matte shade above, black winged liner and full false lashes',
    siren: 'a siren-eye look: eyeliner drawn as a long sharp line stretching far past the outer corner and lifting the eye, a smoked-out lower line, bare lids otherwise and a glossy nude lip',
    dolleyes: 'a doll-eye look: round wide-open eyes with white liner on the waterline, individual spiky lashes on the top and bottom, pale shimmer on the lid centre and a pink cream lip',
    latte: 'a latte look: everything in warm coffee tones — milky-brown eyeshadow blended all over the lid, brown liner, mocha blush and a brown-lined nude lip',
    cherry: 'a cherry look: a glossy deep cherry-red lip with a matching soft cherry blush pressed on the cheeks, clean glowing skin and bare brown eyeshadow',
    festival: 'a festival look: chunky face glitter and rhinestones scattered along the cheekbones and lid corners, bright shimmer eyeshadow and a clear high-shine lip',
    softmatteGulf: 'a Gulf soirée look: heavy black kohl and long lashes, a strongly sculpted contour, matte full-coverage skin, gold shimmer on the inner corners and a muted rosewood matte lip',
    lashliner: 'a tightline look: black liner pressed only into the lash line so the lashes look thicker with no visible line, plus clean skin and a balm lip',
    bridgecontour: 'a nose-focused look: fine contour down the sides of the nose with a bright highlight on the bridge and tip, soft neutral eyes and a nude lip',
    romanticglow: 'a romantic look: rosy blush placed high and softly diffused, dewy skin, pink shimmer on the lids and a rose-tinted glossy lip',
    /* v-studio-100: دفعة الـ١٠٠ شكل (طلب المالك «على الأقلّ ١٠٠ نوع وشكل») */
    wingedliner: 'a sharp black winged eyeliner as the single focus, with clean matte skin, groomed brows, mascara only and a neutral satin lip',
    doubleliner: 'a graphic double wing: the classic black line plus a second thinner line floating above the crease, bare lids between them and a nude lip',
    whiteliner: 'a bright white graphic liner traced along the lash line and inner corners over bare lids, with glowing skin and a clear gloss lip',
    smudgedliner: 'a deliberately smudged soft-black liner blurred all around the eye with a fingertip, messy and lived-in, with bare skin and a balm lip',
    haloeye: 'a halo eye: dark shadow at the inner and outer thirds with a bright shimmer spot in the centre of the lid, plus a soft nude lip',
    sunseteyes: 'sunset eyes: orange, coral and pink shadow blended up into the crease and along the lower lash line, with fresh dewy skin and a peach lip',
    purplesmokey: 'a purple smokey eye in violet and plum tones blended all around the eye, with matte skin, defined brows and a muted rose lip',
    bluesmokey: 'a navy-blue smokey eye with black liner in the waterline, soft bronzed skin and a bare beige lip',
    greensmokey: 'an emerald-green smokey eye softened at the edges with gold shimmer at the centre, clean skin and a brown-nude lip',
    coppereye: 'a copper metallic wash over the whole lid with warm brown blending in the crease, glowy skin and a caramel gloss',
    silvereye: 'a silver foil eye with a cool grey crease, sharp black lashes, porcelain-smooth skin and a pale pink lip',
    glittercut: 'a glitter cut crease: a carved crease line with dense glitter packed on the lid below it, dramatic lashes and a nude lip',
    floatingliner: 'a floating liner drawn in the crease well above the lashes, with bare lids beneath it, clean skin and a glossy nude lip',
    foxeye: 'a fox-eye look: liner extended straight out and lifted at the tail with brushed-up brows for a stretched almond shape, plus a nude lip',
    puppyeye: 'a puppy-eye look: liner dropped slightly at the outer corner and rounded shadow beneath the eye for a soft open gaze, with a pink lip',
    lowerlash: 'the colour placed mainly under the eye: shadow smoked along the lower lash line with bare lids above, and a simple nude lip',
    coloredmascara: 'coloured mascara in a bright shade on the top and bottom lashes as the only eye product, with bare lids, fresh skin and a clear lip',
    spikylashes: 'clumped spiky lashes in separated spikes over a bare lid, with glowing skin, fluffy brows and a peachy balm lip',
    boldbrows: 'strong full brushed-up brows as the main feature, with barely-there eye makeup, clean skin and a neutral lip',
    bleachbrow: 'an editorial look with pale concealed brows, graphic shadow around the eye and a matte flat-toned lip',
    nudeover: 'an overlined nude lip with a slightly darker liner ring and a gloss centre, with soft bronzed eyes and sculpted cheeks',
    ninetieslip: 'a 1990s brown lip: dark brown liner with a lighter matte brown inside, thin brows, warm taupe shadow and matte skin',
    winelip: 'a deep wine lip with soft blurred edges, bare shimmering lids, minimal liner and warm blush',
    fuchsialip: 'a bright fuchsia-pink lip as the single focus, with clean glowing skin, brown mascara and no eyeshadow',
    glasslips: 'ultra-shiny glass lips in a clear high-shine gloss over a nude base, with dewy skin and soft neutral eyes',
    blurredlip: 'a blurred lip: colour patted on and softened at the edges with no sharp line, plus fresh skin and light shimmer on the lids',
    lipstain: 'a sheer berry lip stain that looks like natural colour, with bare lids, groomed brows and skin-like coverage',
    blushdraping: 'blush draping: blush swept from the cheeks up to the temples and onto the lids as the main colour, with a bare glossy lip',
    freckledlook: 'drawn-on freckles over the nose and cheeks with sheer skin, brown mascara, fluffy brows and a clear balm lip',
    strobing: 'strong strobing: intense highlighter on the cheekbones, brow bones, nose bridge and cupid\'s bow with almost no contour and a glossy nude lip',
    heavycontour: 'a heavily sculpted face: deep contour under the cheekbones, jaw and nose with sharp highlight, matte skin and a lined nude lip',
    monochromepink: 'a pink monochrome look: the same pink on the lids, cheeks and lips, with clean skin and simple mascara',
    monochromepeach: 'a peach monochrome look: matching peach shadow, blush and lip over lightly glowing skin',
    cleangirl: 'a clean-girl look: skin tint only, brushed-up brows, brown mascara, a touch of cream blush and a nude balm lip',
    oldmoneymakeup: 'an understated old-money look: satin skin, soft taupe eyes, precise light brows, restrained blush and a muted rose lip',
    igari: 'a Japanese igari look: blush placed high across the nose and under the eyes like a warm flush, with bare lids and a gradient lip',
    arabicglam: 'full Arabic glam: sharp black liner, dense lashes, deep cut crease in warm browns, strong contour and a matte rosewood lip',
    turkishglam: 'Turkish glam: softly smoked bronze eyes, heavy lashes, luminous sculpted skin and a shiny nude-caramel lip',
    bollywoodmakeup: 'a Bollywood look: gold and jewel-toned shadow, heavy kajal, radiant skin, strong blush and a deep red lip',
    sixtiesmod: 'a 1960s mod look: a hard crease cut line, white lid, thick black liner with drawn lower lashes and a pale nude lip',
    seventiesdisco: 'a 1970s disco look: bronze and gold shimmer, brown-blended crease, glowing cheeks and a shiny toffee lip',
    eightiesneon: 'an 1980s neon look: bright blue and pink shadow stacked to the brow, blush swept high and a coral-frost lip',
    ninetiesgrunge: 'a 1990s grunge look: smudged dark liner, matte skin, thin brows and a dark brown-plum lip',
    ytwokfrost: 'a Y2K look: frosted silver-lilac lids, thin liner, pearly highlighter and a frosted pale gloss',
    gothicmakeup: 'a gothic look: black smoked eyes, pale matte skin, sharp contour and a black-cherry matte lip',
    avantgarde: 'an avant-garde look: bold graphic shapes painted around the eye in flat colour, bare skin and a matching flat lip',
    rhinestone: 'rhinestones placed along the inner corners and cheekbones over shimmering skin, with soft neutral eyes and a glossy lip',
    mermaidpearl: 'a pearly mermaid look: iridescent shimmer on the lids and high points, aqua liner and a milky pearl lip',
    butterflyliner: 'graphic butterfly-wing liner drawn at the outer corners in black with fine detail, bare lids and a nude lip',
    hennanightmakeup: 'a henna-night look: warm gold and green-toned shadow, heavy kohl, glowing bronzed skin and a deep berry lip',
    bridalgulf: 'a Gulf bridal look: full-coverage luminous skin, champagne cut crease, dramatic lashes, sharp contour and a rose-nude matte lip',
    bridalindian: 'an Indian bridal look: jewel-toned shadow with gold glitter, heavy kajal, glowing skin, strong blush and a deep red lip',
    engagementsoft: 'a soft engagement look: satin skin, rose-gold lids, fine liner, natural lashes and a muted pink lip',
    eidmakeup: 'a festive Eid look: warm gold shimmer on the lids, bronzed cheeks, glowing skin and a soft coral-nude lip',
    ramadanmakeup: 'a quiet Ramadan look: barely-there skin, soft brown definition on the lash line and a rosy balm lip',
    photoshoothd: 'an HD photography look: matte full-coverage skin, precise contour and highlight, defined eyes and a matte neutral lip that reads on camera',
    tvstudio: 'a broadcast look: shine-free skin, softly defined eyes, neat brows and a mid-tone lip that stays natural under strong lights',
    officemakeup: 'a workday look: light even skin, soft brown lash line, neat brows, a touch of blush and a satin nude lip',
    gymproof: 'a minimal sweat-proof look: tinted brows, waterproof mascara, blurred skin and a tinted lip balm',
    sensitiveminimal: 'an extremely minimal look: no foundation, only brow grooming, clear lash gel and a tinted balm',
    dramaticlashes: 'dramatic full false lashes as the whole look, with clean skin, a thin liner and a bare glossy lip',
    underliner: 'a bright coloured line drawn only along the lower lash line, with bare lids, fresh skin and a clear lip',
    siren2: 'a softer siren eye: a shorter lifted line smoked into the lower corner, glossy lids and a rosy nude lip',
    cherryblush: 'a cherry blush look: deep red-toned blush blended high on the cheeks, bare lids and a matching glossy lip',
    sunkissedfreckle: 'a sun-kissed look: bronzed cheeks and nose, faux freckles, golden highlight and a warm nude gloss',
    porcelain: 'a porcelain look: pale flawless matte skin, cool contour, soft grey eyes and a muted pink lip',
    blackgold: 'a black-and-gold look: black smoked outer corners with gold foil on the lid centre, sculpted skin and a nude lip',
    nudegloss: 'a nude-gloss look: skin-toned glossy lips with a light brown liner, soft neutral eyes and glowing skin',
    sharpcontourlip: 'a precisely lined lip in a mid-brown-rose with a matte finish, with softly bronzed eyes and clean skin',
    duochrome: 'a duochrome eye: a shadow that shifts between two colours as the light moves, over bare skin and a neutral lip',
    smokeybrown: 'a warm brown smokey eye, softer than the black version, with bronzed skin and a caramel-nude lip',
    whitepearleye: 'a pearl-white shimmer washed over the whole lid with a thin brown line, fresh skin and a pale pink lip',
    graphicdots: 'painted white or coloured dots arranged around the eye as a graphic pattern, with bare skin and a neutral lip',
    bronzeglow: 'an all-over bronze glow: bronzer, golden highlighter and a bronze lid wash, finished with a warm gloss',
    coolgirl: 'a cool-toned look: grey-taupe shadow, ashy contour, muted mauve blush and a cool nude lip',
    softpinkeye: 'a soft pink eye: rosy shadow blended all around the eye with no liner, dewy skin and a pink balm lip',
  },
  beard: {
    full: 'a full thick well-groomed beard with a defined neckline and a trimmed moustache',
    stubble: 'light designer stubble, a few days\' growth, evenly trimmed and sharp at the cheek line',
    mustache: 'a neat moustache only, with the cheeks and chin cleanly shaved',
    goatee: 'a neat goatee: hair on the chin and around the mouth only, cheeks shaved',
    clean: 'a completely clean-shaven face with smooth skin and no stubble shadow',
    boxed: 'a short boxed beard with sharply edged cheek and neck lines',
    vandyke: 'a Van Dyke beard: a pointed chin beard with a moustache detached from it',
    faded: 'a beard faded into the haircut at the sideburns, dense at the chin',
    longbeard: 'a thick long beard reaching the chest, well-combed and groomed',
    anchor: 'an anchor beard: a pointed chin strip with a moustache, following the jawline',
    /* v-studio-more-looks */
    ducktail: 'a ducktail beard: full on the cheeks and tapering to a point below the chin',
    chinstrap: 'a thin chinstrap beard tracing the jawline, with the chin and cheeks otherwise shaved',
    circlebeard: 'a circle beard: a rounded moustache joined to a rounded chin beard',
    mutton: 'wide mutton-chop sideburns down the cheeks with a shaved chin',
    greybeard: 'a distinguished salt-and-pepper grey beard, full and neatly shaped',
    shapedbeard: 'a barber-shaped beard with razor-sharp edges on the cheek and neck lines and a subtle fade at the sideburns',
  },
  skin: {
    subtle: 'subtle natural skin smoothing that keeps realistic skin texture and visible pores',
    glow: 'a healthy natural glow with an even skin tone and soft light on the cheekbones',
    circles: 'reduced dark circles under the eyes for a rested, refreshed look',
    tan: 'a healthy sun-kissed golden tan skin tone, even across the face and neck',
    matteskin: 'a shine-free matte refined skin finish with no oily highlights',
    freckles: 'charming natural light freckles scattered over the nose and cheeks',
    /* v-studio-more-looks */
    poreless: 'a smooth poreless finish on the cheeks and nose while keeping the skin looking real, not plastic',
    acneclear: 'clear skin: active blemishes and spots removed, redness calmed, natural texture kept',
    scarfree: 'faded old acne scars and marks, evened out into the surrounding skin tone',
    hydrated: 'plump, well-hydrated skin with fine dryness lines softened and a fresh supple surface',
    evenTone: 'an even skin tone with pigmentation patches and redness balanced out naturally',
    softfilter: 'a soft-focus finish like fine studio diffusion: gentle on texture, still clearly a real photograph',
  },
  glasses: {
    sunglasses: 'classic black rectangular sunglasses with dark lenses',
    round: 'round vintage-style metal glasses with clear lenses',
    catseye: 'cat-eye shaped glasses with lifted outer corners',
    aviator: 'aviator glasses with a thin metal frame and teardrop lenses',
    rimless: 'thin rimless glasses with barely visible edges',
    wayfarer: 'classic thick-framed wayfarer glasses',
    oversized: 'fashionable oversized frame glasses covering the brows',
    sportglasses: 'sleek wraparound sport sunglasses with mirrored lenses',
    goldframe: 'luxury thin gold-frame glasses with clear lenses',
    retroglasses: 'retro 70s glasses with warm brown tinted lenses',
    hexagon: 'modern hexagonal thin-metal frame glasses',
    clearframe: 'trendy clear transparent acetate frame glasses',
    /* v-studio-more-looks */
    browline: 'browline glasses: a thick top bar with a thin metal lower rim',
    octagon: 'octagonal thin gold-rim glasses with clear lenses',
    halfrim: 'half-rim glasses with the frame on the top half only',
    bluelight: 'modern slim computer glasses with a faint blue-violet lens reflection',
    mirrored: 'mirrored sunglasses with a bright reflective silver-blue lens',
    tinyframe: 'tiny narrow trend sunglasses with small dark oval lenses',
  },
  tattoo: {
    sleeve: 'a detailed full arm sleeve tattoo in black and grey shading',
    wrist: 'a small delicate fine-line wrist tattoo',
    back: 'a large detailed back-piece tattoo with heavy shading',
    tribal: 'a bold black tribal tattoo with thick curved bands',
    geometric: 'a fine-line geometric tattoo of interlocking shapes',
    minimalline: 'a tiny minimalist single-line tattoo',
    arabictattoo: 'an elegant Arabic calligraphy tattoo in a flowing script',
    floraltattoo: 'a detailed floral botanical tattoo with fine stippled shading',
    custom: 'a custom tattoo design as described',
    /* v-studio-more-looks */
    japanese: 'a Japanese irezumi tattoo: waves, koi and peony in bold outlines with dense colour',
    blackwork: 'a heavy blackwork tattoo: large areas of solid black with sharp negative-space shapes',
    watercolortattoo: 'a watercolour tattoo with soft colour splashes and paint drips and no black outline',
    necktattoo: 'a small tattoo on the side of the neck, fine-line and delicate',
    chesttattoo: 'a symmetrical chest-piece tattoo spreading across both collarbones',
    ankletattoo: 'a fine tattoo band around the ankle',
    dotwork: 'a dotwork (stippled) mandala tattoo built entirely from tiny black dots',
  },
  anime: {
    classic: 'a classic Japanese anime art style illustration with cel shading and clean line art',
    chibi: 'a cute chibi cartoon style illustration with a huge head and tiny body',
    ghibli: 'a Studio Ghibli-inspired hand-painted anime style with soft watercolour backgrounds',
    cyberpunk: 'a cyberpunk anime art style with neon accents and a rainy night city behind',
    manga: 'a black and white manga ink illustration with screentones and hatching',
    shonenstudio: 'a dynamic shonen action anime style with speed lines and glowing energy',
    kawaii: 'a cute kawaii pastel anime style with sparkles and soft pink tones',
    webtoon: 'a clean modern webtoon comic style with soft gradients and thin line art',
    retro90s: 'a nostalgic 1990s cel anime style with grainy film texture and muted colours',
    /* v-studio-more-looks */
    seinen: 'a mature seinen anime style: realistic proportions, detailed rendering and moody lighting',
    mecha: 'a mecha anime style: the person in a pilot suit with a giant robot looming behind',
    isekai: 'an isekai fantasy anime style: adventurer clothing, a magic aura and a fantasy landscape behind',
    magicalgirl: 'a magical-girl anime style: a frilly transformation outfit, ribbons, sparkles and a glowing wand',
    cinematicanime: 'a cinematic anime-film style: painterly backgrounds, film-grade lighting and a wide movie frame feel',
    sportanime: 'a sports anime style: a team uniform, sweat and motion, a stadium and dramatic angle',
    shojo: 'a shojo anime style: huge sparkling eyes, flower petals in the air and soft pastel screentones',
  },
  heritage: {
    kandora: 'a traditional Gulf men\'s kandora (dishdasha) with a matching ghutra headscarf and agal',
    bisht: 'a luxurious traditional Gulf bisht cloak with gold trim worn over a white kandora',
    abaya: 'an elegant traditional women\'s black abaya with a matching sheila headscarf',
    embroidered: 'a richly embroidered traditional Gulf women\'s dress (thobe nashal) with gold detailing',
    saudi: 'a traditional Saudi men\'s thobe with a red-and-white shemagh headscarf',
    emirati: 'a traditional Emirati women\'s kaftan with delicate hand embroidery',
    omani: 'a traditional Omani men\'s dishdasha with an embroidered kummah cap',
    saudimen2: 'a Saudi winter bisht worn over a thobe with a red shemagh, a stately look',
    moroccanher: 'a Moroccan djellaba with a hood and fine stitching',
    palestinian: 'a Palestinian embroidered thobe with traditional tatreez patterns',
    /* v-studio-more-looks */
    kuwaitiher: 'a traditional Kuwaiti daraa: a loose embroidered dress with gold zari trim at the neckline and cuffs',
    qatarither: 'a traditional Qatari thobe al-nashal in a deep jewel tone with heavy gold thread embroidery',
    bahrainiher: 'a traditional Bahraini dress with fine pearl-inspired embroidery and a light sheila',
    omaniwomen: 'traditional Omani women\'s dress: a brightly coloured embroidered tunic with sirwal trousers and a lihaf headscarf',
    yemeni: 'a traditional Yemeni look: a patterned wrap (maawaz) with an embroidered belt, or a Sanaani embroidered dress',
    egyptian: 'a traditional Egyptian galabeya with a woven sash and simple embroidery at the neck',
    sudanesedress: 'a traditional Sudanese look: a colourful wrapped thobe for women, or a white jalabiya with an imma turban for men',
    levantine: 'a traditional Levantine look: a cross-stitch embroidered thobe for women, or a sherwal with a vest and a hatta for men',
  },
};

/* ───── وصف المعاينة للميزات الأساسيّة (نفس نظام studio-more للميزات الـ١٤):
   التأطير يجب أن يُظهر الميزة نفسها — صور المكياج الجاهزة كانت جسمًا كاملًا
   فبدت الخيارات العشرة صورة واحدة. ───── */
const PREVIEW_FRAME = {
  hair: 'head-and-shoulders portrait, the hair colour and cut fully visible and in focus',
  nails: 'close-up of one hand raised near the face, the fingernails filling much of the frame and sharply in focus',
  makeup: 'tight close-up beauty portrait of the face only, the eyes and lips sharply in focus, the makeup clearly readable',
  beard: 'head-and-shoulders portrait, the facial hair sharply in focus',
  skin: 'tight close-up beauty portrait of the face, the skin texture and finish clearly visible',
  glasses: 'head-and-shoulders portrait, the glasses front-facing and clearly visible',
  tattoo: 'close-up of the tattooed area, the tattoo artwork sharp and clearly visible',
  anime: 'upper-body character illustration, the art style clearly readable',
  heritage: 'three-quarter portrait, the traditional outfit and headwear fully visible',
};
const PREVIEW_FEATURE_NAME = {
  hair: 'the hair colour or hairstyle', nails: 'the nail design', makeup: 'the makeup look',
  beard: 'the beard style', skin: 'the skin finish', glasses: 'the glasses',
  tattoo: 'the tattoo', anime: 'the art style', heritage: 'the heritage outfit',
};
/* جنس نموذج المعاينة: الافتراضيّ للميزة في __tab، والاستثناءات بالخيار */
const PREVIEW_SUBJECT = {
  hair: { __tab: 'w' },
  nails: { __tab: 'w' },
  makeup: { __tab: 'w' },
  beard: { __tab: 'm' },
  skin: { __tab: 'w' },
  glasses: { __tab: 'w', aviator: 'm', wayfarer: 'm', sportglasses: 'm', browline: 'm', mirrored: 'm', bluelight: 'm' },
  tattoo: { __tab: 'm', wrist: 'w', minimalline: 'w', floraltattoo: 'w', ankletattoo: 'w', necktattoo: 'w' },
  anime: { __tab: 'w', shonenstudio: 'm', mecha: 'm', seinen: 'm', sportanime: 'm', isekai: 'm' },
  heritage: {
    __tab: 'm', kandora: 'm', bisht: 'm', saudi: 'm', omani: 'm', saudimen2: 'm', moroccanher: 'm',
    abaya: 'w', embroidered: 'w', emirati: 'w', palestinian: 'w', kuwaitiher: 'w', qatarither: 'w',
    bahrainiher: 'w', omaniwomen: 'w', yemeni: 'm', egyptian: 'm', sudanesedress: 'w', levantine: 'w',
  },
};

module.exports = { STYLE_TEXT, PREVIEW_FRAME, PREVIEW_FEATURE_NAME, PREVIEW_SUBJECT };
